export function buildTypography(primary: string) {
    return {
        fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
        h4: { fontWeight: 600 },
        h6: { fontWeight: 600 },
        tabTitle: {
            fontWeight: 600,
            fontSize: "1rem",
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
            flex: 1,
            minWidth: 0,
        },
        portalPageTitle: {
            fontSize: "2rem",
            fontWeight: 700,
            color: primary,
            textAlign: "center" as const,
            marginBottom: "12px",
            lineHeight: 1.2,
            display: "block",
        },
        portalPageSubtitle: {
            fontSize: "1.125rem",
            fontWeight: 400,
            color: "#4A5568",
            textAlign: "center" as const,
            marginBottom: "24px",
            lineHeight: 1.5,
            display: "block",
        },
        portalSectionTitle: {
            fontSize: "1.5rem",
            fontWeight: 600,
            color: "#2D3748",
            marginBottom: "16px",
            lineHeight: 1.3,
        },
        portalCardTitle: {
            fontSize: "1.125rem",
            fontWeight: 600,
            color: "#2D3748",
            marginBottom: "8px",
            lineHeight: 1.4,
        },
        portalCardSubtitle: {
            fontSize: "0.875rem",
            fontWeight: 400,
            color: "#718096",
            lineHeight: 1.5,
        },
        portalActionButton: {
            fontSize: "0.875rem",
            fontWeight: 600,
            textTransform: "none",
            color: primary,
        },
        portalStatusText: {
            fontSize: "0.875rem",
            fontWeight: 500,
            lineHeight: 1.4,
        },
        listPageHeaderTitle: {
            fontSize: "1.75rem",
            fontWeight: 700,
            lineHeight: 1.2,
            color: "#2D3748",
        },
        listPageHeaderDescription: {
            fontSize: "0.875rem",
            fontWeight: 500,
            color: "#718096",
            lineHeight: 1.5,
        },
        hebrewTitle: {
            fontSize: "1.75rem",
            fontWeight: 700,
            lineHeight: 1.2,
            color: "#2D3748",
            textAlign: "right" as const,
            direction: "rtl" as const,
        },
        hebrewSubtitle: {
            fontSize: "0.875rem",
            fontWeight: 500,
            color: "#718096",
            textAlign: "right" as const,
            direction: "rtl" as const,
            lineHeight: 1.5,
        },
        hebrewCardTitle: {
            fontSize: "0.8rem",
            fontWeight: 500,
            color: "#7C8DA1",
            textAlign: "right" as const,
            direction: "rtl" as const,
            textTransform: "uppercase",
            letterSpacing: "0.5px",
            lineHeight: 1.4,
        },
        hebrewCardSubtitle: {
            fontSize: "1.75rem",
            fontWeight: 700,
            color: primary,
            textAlign: "right" as const,
            direction: "rtl" as const,
            lineHeight: 1,
        },
        hebrewBodyText: {
            fontSize: "0.875rem",
            fontWeight: 400,
            color: "#374151",
            textAlign: "right" as const,
            direction: "rtl" as const,
            lineHeight: 1.5,
        },
    };
}
