/**
 * Generated by `npm run generate:db-types` from the Nest prisma schema.
 * Do not edit by hand — rerun the script when the schema changes.
 *
 * These mirror the API row shapes the frontend receives from Nest. They are
 * plain structural types: no Prisma client, no database access.
 */

/* eslint-disable @typescript-eslint/no-explicit-any, no-redeclare */

export type JsonValue =
    | string
    | number
    | boolean
    | null
    | JsonValue[]
    | { [key: string]: JsonValue };

/** Prisma `Decimal` columns arrive as JSON numbers (or strings for wide values). */
export type Decimal = number | string;

export const activity_status = {
    SCHEDULED: "SCHEDULED",
    SENT: "SENT",
    DELIVERED: "DELIVERED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    PAUSED: "PAUSED",
    BOUNCED: "BOUNCED",
    DISPUTE: "DISPUTE",
    COMPLETED: "COMPLETED",
} as const;
export type activity_status = (typeof activity_status)[keyof typeof activity_status];

export const activity_type = {
    SMS: "SMS",
    Email: "Email",
    Call: "Call",
    WhatsApp: "WhatsApp",
    Internal: "Internal",
    Resolved: "Resolved",
    Dispute: "Dispute",
    Promise_to_pay: "Promise_to_pay",
    Agent: "Agent",
} as const;
export type activity_type = (typeof activity_type)[keyof typeof activity_type];

export const attachment_category = {
    Text: "Text",
    Image: "Image",
    Audio: "Audio",
} as const;
export type attachment_category = (typeof attachment_category)[keyof typeof attachment_category];

export const BillingConnectorStatus = {
    Active: "Active",
    Disabled: "Disabled",
    Error: "Error",
} as const;
export type BillingConnectorStatus = (typeof BillingConnectorStatus)[keyof typeof BillingConnectorStatus];

export const BillingProvider = {
    PRIORITY: "PRIORITY",
    SAP_BUSINESS_ONE: "SAP_BUSINESS_ONE",
} as const;
export type BillingProvider = (typeof BillingProvider)[keyof typeof BillingProvider];

export const category = {
    Automated: "Automated",
    Promise_to_pay: "Promise_to_pay",
    Dispute: "Dispute",
    Agent: "Agent",
    Legal: "Legal",
} as const;
export type category = (typeof category)[keyof typeof category];

export const client_type = {
    Company: "Company",
    Person: "Person",
} as const;
export type client_type = (typeof client_type)[keyof typeof client_type];

export const ConnectorAuthType = {
    API_KEY: "API_KEY",
    OAUTH2_CLIENT_CREDENTIALS: "OAUTH2_CLIENT_CREDENTIALS",
    BASIC: "BASIC",
} as const;
export type ConnectorAuthType = (typeof ConnectorAuthType)[keyof typeof ConnectorAuthType];

export const ConnectorSyncMode = {
    BACKFILL: "BACKFILL",
    INCREMENTAL: "INCREMENTAL",
} as const;
export type ConnectorSyncMode = (typeof ConnectorSyncMode)[keyof typeof ConnectorSyncMode];

export const contact_priority = {
    Primary: "Primary",
    Secondary: "Secondary",
    Emergency: "Emergency",
} as const;
export type contact_priority = (typeof contact_priority)[keyof typeof contact_priority];

export const contact_status = {
    Active: "Active",
    Inactive: "Inactive",
} as const;
export type contact_status = (typeof contact_status)[keyof typeof contact_status];

export const cost_calculation_method = {
    ActualSales: "ActualSales",
    Limit: "Limit",
} as const;
export type cost_calculation_method = (typeof cost_calculation_method)[keyof typeof cost_calculation_method];

export const customer_client_type = {
    Company: "Company",
    Person: "Person",
    All: "All",
} as const;
export type customer_client_type = (typeof customer_client_type)[keyof typeof customer_client_type];

export const customer_limit_type = {
    DCL: "DCL",
    Named: "Named",
} as const;
export type customer_limit_type = (typeof customer_limit_type)[keyof typeof customer_limit_type];

export const customer_top_up_type = {
    Fixed: "Fixed",
    Percentage: "Percentage",
} as const;
export type customer_top_up_type = (typeof customer_top_up_type)[keyof typeof customer_top_up_type];

export const delivery_status = {
    Scheduled: "Scheduled",
    Sent: "Sent",
    Delivered: "Delivered",
    Bounced: "Bounced",
    Failed: "Failed",
    Pending: "Pending",
    Cancelled: "Cancelled",
} as const;
export type delivery_status = (typeof delivery_status)[keyof typeof delivery_status];

export const dispute_resolution = {
    Denied: "Denied",
    Accepted_Settled_partly: "Accepted_Settled_partly",
    Accepted_Settled_in_full: "Accepted_Settled_in_full",
    Accepted: "Accepted",
    Cancelled: "Cancelled",
    Admin_Fixed_Balance_Unchanged: "Admin_Fixed_Balance_Unchanged",
} as const;
export type dispute_resolution = (typeof dispute_resolution)[keyof typeof dispute_resolution];

export const dispute_status = {
    New: "New",
    Under_Review: "Under_Review",
    Awaiting_Update: "Awaiting_Update",
    Resolved: "Resolved",
    Cancelled: "Cancelled",
} as const;
export type dispute_status = (typeof dispute_status)[keyof typeof dispute_status];

export const email_status = {
    Valid: "Valid",
    Bounced: "Bounced",
    Failure: "Failure",
} as const;
export type email_status = (typeof email_status)[keyof typeof email_status];

export const ImportRecordStatus = {
    Pending: "Pending",
    Validated: "Validated",
    Processing: "Processing",
    Success: "Success",
    Failed: "Failed",
    Skipped: "Skipped",
} as const;
export type ImportRecordStatus = (typeof ImportRecordStatus)[keyof typeof ImportRecordStatus];

export const ImportStatus = {
    Pending: "Pending",
    Processing: "Processing",
    Completed: "Completed",
    Failed: "Failed",
    Cancelled: "Cancelled",
} as const;
export type ImportStatus = (typeof ImportStatus)[keyof typeof ImportStatus];

export const ImportType = {
    Invoice: "Invoice",
    Customer: "Customer",
    Contact: "Contact",
    Payment: "Payment",
    Policy: "Policy",
} as const;
export type ImportType = (typeof ImportType)[keyof typeof ImportType];

export const insurance_policy_kind = {
    Primary: "Primary",
    TopUp: "TopUp",
} as const;
export type insurance_policy_kind = (typeof insurance_policy_kind)[keyof typeof insurance_policy_kind];

export const internal_email_template_type = {
    dispute_assignment: "dispute_assignment",
    dispute_created: "dispute_created",
    dispute_resolved: "dispute_resolved",
    dispute_updated: "dispute_updated",
    credit_insurance_alert: "credit_insurance_alert",
} as const;
export type internal_email_template_type = (typeof internal_email_template_type)[keyof typeof internal_email_template_type];

export const invoice_reported_status = {
    Reported: "Reported",
    Acknowledge_Received: "Acknowledge_Received",
} as const;
export type invoice_reported_status = (typeof invoice_reported_status)[keyof typeof invoice_reported_status];

export const invoice_status = {
    Open: "Open",
    Paid: "Paid",
    Overdue: "Overdue",
    Partially_Paid: "Partially_Paid",
    Void: "Void",
    Under_Dispute: "Under_Dispute",
    Due: "Due",
    Draft: "Draft",
    Sent: "Sent",
    Viewed: "Viewed",
    Cancelled: "Cancelled",
} as const;
export type invoice_status = (typeof invoice_status)[keyof typeof invoice_status];

export const language = {
    English: "English",
    Hebrew: "Hebrew",
    German: "German",
    Spanish: "Spanish",
    French: "French",
    Italian: "Italian",
    Portuguese: "Portuguese",
} as const;
export type language = (typeof language)[keyof typeof language];

export const log_level = {
    DEBUG: "DEBUG",
    INFO: "INFO",
    WARNING: "WARNING",
    ERROR: "ERROR",
    CRITICAL: "CRITICAL",
} as const;
export type log_level = (typeof log_level)[keyof typeof log_level];

export const mobile_status = {
    Valid: "Valid",
    Failure: "Failure",
} as const;
export type mobile_status = (typeof mobile_status)[keyof typeof mobile_status];

export const notification_delivery_channel = {
    in_app: "in_app",
    email: "email",
} as const;
export type notification_delivery_channel = (typeof notification_delivery_channel)[keyof typeof notification_delivery_channel];

export const notification_rule_product = {
    credit_insurance: "credit_insurance",
    collection: "collection",
} as const;
export type notification_rule_product = (typeof notification_rule_product)[keyof typeof notification_rule_product];

export const notification_rule_trigger_type = {
    overdue_block: "overdue_block",
    capacity_gap: "capacity_gap",
    entry_terms_breach: "entry_terms_breach",
    action_window: "action_window",
    limit_warnings: "limit_warnings",
} as const;
export type notification_rule_trigger_type = (typeof notification_rule_trigger_type)[keyof typeof notification_rule_trigger_type];

export const notification_type = {
    Primary: "Primary",
    Secondary: "Secondary",
} as const;
export type notification_type = (typeof notification_type)[keyof typeof notification_type];

export const priority = {
    Low: "Low",
    Normal: "Normal",
    High: "High",
} as const;
export type priority = (typeof priority)[keyof typeof priority];

export const record_status = {
    Active: "Active",
    Inactive: "Inactive",
    Draft: "Draft",
} as const;
export type record_status = (typeof record_status)[keyof typeof record_status];

export const sms_status = {
    Scheduled: "Scheduled",
    Sent: "Sent",
    Delivered: "Delivered",
    Failed: "Failed",
    Rejected: "Rejected",
    Pending: "Pending",
    Cancelled: "Cancelled",
} as const;
export type sms_status = (typeof sms_status)[keyof typeof sms_status];

export const step_type = {
    due: "due",
    overdue: "overdue",
} as const;
export type step_type = (typeof step_type)[keyof typeof step_type];

export const user_role = {
    archaser_admin: "archaser_admin",
    Account_Manager: "Account_Manager",
    Bookkeeper: "Bookkeeper",
    CFO: "CFO",
    Collection_Manager: "Collection_Manager",
    Collection_Agent: "Collection_Agent",
    Data_Analyst: "Data_Analyst",
    Customer_Service_Representative: "Customer_Service_Representative",
    Auditor: "Auditor",
    IT_Support: "IT_Support",
    System_Administrator: "System_Administrator",
} as const;
export type user_role = (typeof user_role)[keyof typeof user_role];

export type Account = {
    id: number;
    created_at: Date;
    name: string | null;
    address_line1: string | null;
    city: string | null;
    postal_code: string | null;
    address_line2: string | null;
    country_id: number | null;
    promise_to_pay: number;
    modified_at: Date;
    state_id: number | null;
    company_number: string | null;
    client_type: customer_client_type;
    sms_from_name: string | null;
    status: record_status;
    sub_domain: string | null;
    no_of_auomated_steps: number;
    category_after_automated: category | null;
    allow_partial_payment: boolean;
    bank_comments: string | null;
    logo: string | null;
    primary_color: string | null;
    secondary_color: string | null;
    chart_palette_color: string | null;
    default_language: language | null;
    start_days_after_due: number;
    email_from_name: string | null;
    email_server_host: string | null;
    email_from: string | null;
    email_server_user: string | null;
    email_server_password: string | null;
    email_server_port: number | null;
    currency: string | null;
    wait_days_after_automated: number;
    max_promise_to_pay_allowed_per_cycle: number | null;
    locale: string | null;
    next_activity_date: Date | null;
    beneficiary_name: string | null;
    bank_name: string | null;
    branch_number: string | null;
    branch_name: string | null;
    swift: string | null;
    iban: string | null;
    account_number: string | null;
    balance_evaluation_method: string | null;
    generic_field_config: JsonValue | null;
    use_customer_language: boolean | null;
    last_sync_date: Date | null;
    default_first_activity_delay_days: number | null;
    sms_fallback_enabled: boolean | null;
    unlisted_country_sms_policy: string | null;
    intelligent_channel_selection_enabled: boolean | null;
    category_for_new_collection: category | null;
    portal_verification_enabled: boolean | null;
    sso_enabled: boolean | null;
    sso_providers: string | null;
    has_collection: boolean;
    has_credit_insurance: boolean;
    enable_customer_checkpoints: boolean;
    credit_limit_warning_threshold_pct: number | null;
    credit_score_validity_warning_days: number | null;
    reporting_date_warning_days: number | null;
    customer_limit_expiration_warning_days: number | null;
    created_by: string | null;
    modified_by: string | null;
    deleted_at: Date | null;
    deleted_by: string | null;
};

export type AccountRelations = {
    User_Account_created_byToUser: User | null;
    User_Account_modified_byToUser: User | null;
    User_Account_deleted_byToUser: User | null;
    Country: Country | null;
    State: State | null;
    AccountBankAccounts: AccountBankAccounts[];
    AccountSMSProviderPreferences: AccountSMSProviderPreferences[];
    ActivitiesSequence: ActivitiesSequence[];
    ActivitiesTemplate: ActivitiesTemplate[];
    Activity: Activity[];
    ActivityAttachment: ActivityAttachment[];
    BusinessUnitBankAccounts: BusinessUnitBankAccounts[];
    CustomerBanks: CustomerBanks[];
    DisputeReason: DisputeReason[];
    ImportJob: ImportJob[];
    InternalEmailTemplate: InternalEmailTemplate[];
    Invoice: Invoice[];
    InvoicePayment: InvoicePayment[];
    Log: Log[];
    Notification: Notification[];
    NotificationRuleSet: NotificationRuleSet[];
    NotificationDeliveryLog: NotificationDeliveryLog[];
    Payment: Payment[];
    SequenceContainer: SequenceContainer[];
    User_User_account_idToAccount: User[];
    BusinessUnit: BusinessUnit[];
    RolePermission: RolePermission[];
    Customer: Customer[];
    InsurancePolicy: InsurancePolicy[];
    Report: Report[];
    BillingConnector: BillingConnector | null;
    CustomerCheckpoint: CustomerCheckpoint[];
};

export type AccountBankAccounts = {
    id: number;
    created_at: Date;
    modified_at: Date;
    account_id: number;
    beneficiary_name: string | null;
    branch_number: string | null;
    account_number: string | null;
    bank_name: string | null;
    branch_name: string | null;
    swift: string | null;
    iban: string | null;
    comments: string | null;
    status: boolean;
    address_line1: string | null;
    city: string | null;
    postal_code: string | null;
    address_line2: string | null;
    country_id: number | null;
    primary: boolean;
    state_id: number | null;
    created_by: string | null;
    modified_by: string | null;
};

export type AccountBankAccountsRelations = {
    User_AccountBankAccounts_created_byToUser: User | null;
    User_AccountBankAccounts_modified_byToUser: User | null;
    Account: Account;
    Country: Country | null;
    State: State | null;
    BusinessUnitBankAccounts: BusinessUnitBankAccounts[];
    CustomerBanks: CustomerBanks[];
};

export type AccountSMSProviderPreferences = {
    id: number;
    account_id: number;
    country_id: number;
    vendor_id: number;
    is_enabled: boolean | null;
    priority: number | null;
    created_at: Date | null;
    modified_at: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type AccountSMSProviderPreferencesRelations = {
    User_AccountSMSProviderPreferences_created_byToUser: User | null;
    User_AccountSMSProviderPreferences_modified_byToUser: User | null;
    Account: Account;
    Country: Country;
    SMSVendor: SMSVendor;
};

export type ActivitiesSequence = {
    id: number;
    created_at: Date;
    modified_at: Date;
    step: number | null;
    active: boolean;
    activity_type: activity_type;
    category: category;
    days_from_prev_step: number | null;
    step_type: step_type | null;
    days_before_due: number | null;
    account_id: number;
    activity_template_id: number | null;
    master_template: boolean | null;
    last_category_step: boolean;
    time_of_day: string | null;
    days_after_start: number | null;
    send_to_escalated_contacts: boolean | null;
    send_to_standard_contacts: boolean | null;
    sequence_container_id: number | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ActivitiesSequenceRelations = {
    User_ActivitiesSequence_created_byToUser: User | null;
    User_ActivitiesSequence_modified_byToUser: User | null;
    Account: Account;
    ActivitiesTemplate: ActivitiesTemplate | null;
    SequenceContainer: SequenceContainer | null;
    Activity: Activity[];
};

export type ActivitiesTemplate = {
    id: number;
    created_at: Date;
    modified_at: Date;
    name: string;
    category: category | null;
    language: language | null;
    active: boolean | null;
    account_id: number;
    master_template: boolean | null;
    dispute_resolution: dispute_resolution | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ActivitiesTemplateRelations = {
    ActivitiesSequence: ActivitiesSequence[];
    Account: Account;
    User_ActivitiesTemplate_created_byToUser: User | null;
    User_ActivitiesTemplate_modified_byToUser: User | null;
    Activity: Activity[];
    ActivityTemplateLanguage: ActivityTemplateLanguage[];
};

export type Activity = {
    id: bigint;
    created_at: Date;
    modified_at: Date;
    customer_id: number;
    title: string | null;
    content: string;
    type: activity_type;
    collection_period_id: number | null;
    invoice_id: number | null;
    schedule_time: Date;
    actual_delivery_time: Date | null;
    status_reason: string | null;
    last_sent_time: Date | null;
    contact_id: number | null;
    activity_sequence_id: number | null;
    email: string | null;
    mobile: string | null;
    activity_template: number | null;
    account_id: number;
    is_last_step: boolean;
    system_generated: boolean;
    title_params: JsonValue | null;
    schedule_calculation: string | null;
    status: activity_status;
    call_outcome: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ActivityRelations = {
    User_Activity_created_byToUser: User | null;
    User_Activity_modified_byToUser: User | null;
    Account: Account;
    ActivitiesSequence: ActivitiesSequence | null;
    ActivitiesTemplate: ActivitiesTemplate | null;
    CustomerCollectionPeriod: CustomerCollectionPeriod | null;
    Invoice: Invoice | null;
    Contact: Contact | null;
    Customer: Customer;
    ActivityAttachment: ActivityAttachment[];
    ActivityContact: ActivityContact[];
    CommunicationLearningData: CommunicationLearningData[];
};

export type ActivityAttachment = {
    id: bigint;
    created_at: Date;
    modified_at: Date;
    activity_id: bigint;
    file_name: string;
    file_path: string;
    file_size: number;
    file_type: string;
    file_category: attachment_category;
    uploaded_by: string;
    account_id: number;
    created_by: string | null;
    modified_by: string | null;
};

export type ActivityAttachmentRelations = {
    User_ActivityAttachment_created_byToUser: User | null;
    User_ActivityAttachment_modified_byToUser: User | null;
    Account: Account;
    Activity: Activity;
};

export type ActivityContact = {
    id: number;
    activity_id: bigint;
    contact_id: number;
    message_id: string | null;
    status: delivery_status | null;
    sent_at: Date | null;
    delivered_at: Date | null;
    failed_at: Date | null;
    failure_reason: string | null;
    retry_count: number | null;
    created_at: Date | null;
    modified_at: Date | null;
    sms_vendor_id: number | null;
    sms_cost: Decimal | null;
    sms_currency: string | null;
    sms_segments: number | null;
    sms_encoding: string | null;
    email_opened_at: Date | null;
    email_clicked_at: Date | null;
    email_open_count: number | null;
    email_click_count: number | null;
    communication_channel: activity_type | null;
    is_fallback_attempt: boolean | null;
    original_contact_id: number | null;
    response_received_at: Date | null;
    response_channel: activity_type | null;
    escalation_level: number | null;
    channel_selection_reason: string | null;
    predicted_success_rate: Decimal | null;
    alternative_channels_considered: JsonValue | null;
    ses_message_id: string | null;
    bounced_at: Date | null;
    complaint_at: Date | null;
    bounce_type: string | null;
    bounce_sub_type: string | null;
    clicked_link: string | null;
    vendor_message_id: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ActivityContactRelations = {
    User_ActivityContact_created_byToUser: User | null;
    User_ActivityContact_modified_byToUser: User | null;
    Activity: Activity;
    Contact: Contact;
    ActivityContact: ActivityContact | null;
    other_ActivityContact: ActivityContact[];
    SMSVendor: SMSVendor | null;
};

export type ActivityTemplateLanguage = {
    id: number;
    created_at: Date;
    modified_at: Date;
    template_id: number;
    language: string;
    sms_content: string | null;
    whatsapp_content: string | null;
    email_subject: string | null;
    email_content: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ActivityTemplateLanguageRelations = {
    User_ActivityTemplateLanguage_created_byToUser: User | null;
    User_ActivityTemplateLanguage_modified_byToUser: User | null;
    ActivitiesTemplate: ActivitiesTemplate;
};

export type BillingConnector = {
    id: number;
    account_id: number;
    provider: BillingProvider;
    status: BillingConnectorStatus;
    base_url: string | null;
    auth_type: ConnectorAuthType;
    credentials_encrypted: string | null;
    sync_enabled: boolean;
    sync_cron_expression: string;
    sync_mode: ConnectorSyncMode;
    enabled_entities: JsonValue;
    sync_overlap_minutes: number;
    backfill_max_pages_per_run: number;
    backfill_max_duration_seconds: number;
    backfill_import_batch_size: number;
    consecutive_auth_failures: number;
    backfill_started_at: Date | null;
    last_connection_test_at: Date | null;
    last_connection_error: string | null;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type BillingConnectorRelations = {
    Account: Account;
    ConnectorFieldMapping: ConnectorFieldMapping[];
    ConnectorSyncState: ConnectorSyncState[];
};

export type BusinessUnit = {
    id: number;
    account_id: number;
    name: string;
    parent_id: number | null;
    external_id: string | null;
    status: record_status;
    is_primary: boolean;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type BusinessUnitRelations = {
    Account: Account;
    Parent: BusinessUnit | null;
    Children: BusinessUnit[];
    User_BusinessUnit_created_byToUser: User | null;
    User_BusinessUnit_modified_byToUser: User | null;
    BusinessUnitBankAccounts: BusinessUnitBankAccounts[];
    Customer: Customer[];
    User: User[];
    CreditDashboardDailySnapshot: CreditDashboardDailySnapshot[];
};

export type BusinessUnitBankAccounts = {
    id: number;
    business_unit_id: number;
    account_id: number;
    bank_account_id: number;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type BusinessUnitBankAccountsRelations = {
    BusinessUnit: BusinessUnit;
    Account: Account;
    AccountBankAccounts: AccountBankAccounts;
};

export type CommunicationChannelPreference = {
    id: number;
    customer_id: number;
    channel: activity_type;
    success_rate: Decimal | null;
    response_time_hours: Decimal | null;
    last_successful_contact: Date | null;
    total_attempts: number | null;
    total_successes: number | null;
    preferred_time_of_day: string | null;
    created_at: Date | null;
    modified_at: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type CommunicationChannelPreferenceRelations = {
    User_CommunicationChannelPreference_created_byToUser: User | null;
    User_CommunicationChannelPreference_modified_byToUser: User | null;
    Customer: Customer;
};

export type CommunicationLearningData = {
    id: number;
    customer_id: number;
    contact_id: number | null;
    channel: activity_type;
    activity_id: bigint | null;
    sent_at: Date;
    response_received_at: Date | null;
    response_channel: activity_type | null;
    success: boolean;
    response_time_hours: Decimal | null;
    context_data: JsonValue | null;
    created_at: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type CommunicationLearningDataRelations = {
    User_CommunicationLearningData_created_byToUser: User | null;
    User_CommunicationLearningData_modified_byToUser: User | null;
    Activity: Activity | null;
    Contact: Contact | null;
    Customer: Customer;
};

export type Company = {
    id: number;
    created_at: Date;
    modified_at: Date;
    name: string;
    company_number: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type CompanyRelations = {
    User_Company_created_byToUser: User | null;
    User_Company_modified_byToUser: User | null;
    Contact: Contact[];
    Customer: Customer[];
};

export type ConnectorFieldMapping = {
    id: number;
    connector_id: number;
    import_type: ImportType;
    mapping: JsonValue;
    is_complete: boolean;
    modified_at: Date;
    modified_by: string | null;
};

export type ConnectorFieldMappingRelations = {
    BillingConnector: BillingConnector;
};

export type ConnectorSyncState = {
    id: number;
    connector_id: number;
    entity_type: ImportType;
    backfill_completed: boolean;
    backfill_completed_at: Date | null;
    backfill_cursor: string | null;
    backfill_records_pulled: number;
    backfill_last_checkpoint_at: Date | null;
    backfill_window_end: Date | null;
    backfill_total_records: number | null;
    last_max_updated_at: Date | null;
    last_successful_run_at: Date | null;
    last_attempt_at: Date | null;
    last_error: string | null;
};

export type ConnectorSyncStateRelations = {
    BillingConnector: BillingConnector;
};

export type Contact = {
    id: number;
    created_at: Date;
    modified_at: Date;
    first_name: string;
    last_name: string | null;
    full_name: string | null;
    date_of_birth: Date | null;
    company_id: number;
    status: contact_status;
    email: string | null;
    phone: string | null;
    mobile: string | null;
    role: string | null;
    communication_priority: notification_type | null;
    preferred_communication: activity_type;
    ext_id: string | null;
    company_wide_address: boolean | null;
    email_status: email_status | null;
    receives_standard_reminder: boolean | null;
    receives_escalated_reminder: boolean | null;
    mobile_status: mobile_status | null;
    priority_level: contact_priority | null;
    fallback_contact_id: number | null;
    preferred_channels: string[];
    response_history: JsonValue | null;
    availability_schedule: JsonValue | null;
    escalation_delay_hours: number | null;
    country_id: number | null;
    state_id: number | null;
    customer_id: number | null;
    email_bounce_count: number | null;
    last_email_bounce: Date | null;
    sms_delivery_failure_count: number | null;
    last_sms_failure: Date | null;
    communication_score: Decimal | null;
    generic_text1: string | null;
    generic_text2: string | null;
    generic_number1: number | null;
    generic_number2: number | null;
    generic_date1: Date | null;
    generic_date2: Date | null;
    erp_contact_id: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ContactRelations = {
    Activity: Activity[];
    ActivityContact: ActivityContact[];
    CommunicationLearningData: CommunicationLearningData[];
    User_Contact_created_byToUser: User | null;
    User_Contact_modified_byToUser: User | null;
    Company: Company;
    Country: Country | null;
    Customer: Customer | null;
    Contact: Contact | null;
    other_Contact: Contact[];
    State: State | null;
};

export type Country = {
    id: number;
    name: string;
    iso3: string | null;
    numeric_code: string | null;
    iso2: string | null;
    phonecode: string | null;
    capital: string | null;
    currency: string | null;
    currency_name: string | null;
    currency_symbol: string | null;
    tld: string | null;
    native: string | null;
    region: string | null;
    region_id: number | null;
    subregion: string | null;
    subregion_id: number | null;
    nationality: string | null;
    translations: string | null;
    latitude: Decimal | null;
    longitude: Decimal | null;
    emoji: string | null;
    emojiU: string | null;
    created_at: Date | null;
    modified_at: Date;
    flag: number;
    wikiDataId: string | null;
};

export type CountryRelations = {
    Account: Account[];
    AccountBankAccounts: AccountBankAccounts[];
    AccountSMSProviderPreferences: AccountSMSProviderPreferences[];
    Contact: Contact[];
    CountrySMSVendor: CountrySMSVendor[];
    State: State[];
    Customer: Customer[];
    InsurancePolicyCountry: InsurancePolicyCountry[];
};

export type CountrySMSVendor = {
    id: number;
    country_id: number;
    vendor_id: number;
    is_default: boolean | null;
    is_active: boolean | null;
    created_at: Date | null;
    modified_at: Date | null;
    cost_per_sms: Decimal | null;
    currency: string | null;
    comment: string | null;
    phone_number: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type CountrySMSVendorRelations = {
    User_CountrySMSVendor_created_byToUser: User | null;
    User_CountrySMSVendor_modified_byToUser: User | null;
    Country: Country;
    SMSVendor: SMSVendor;
};

export type CreditAsOfBackfillJob = {
    id: bigint;
    account_id: number;
    status: string;
    from_date: Date | null;
    to_date: Date | null;
    checkpoint_date: Date | null;
    days_total: number;
    days_done: number;
    last_error: string | null;
    requested_by: string | null;
    started_at: Date | null;
    created_at: Date;
    updated_at: Date;
};

export type CreditAsOfRewriteQueue = {
    id: bigint;
    account_id: number;
    customer_ids: number[];
    from_date: Date;
    to_date: Date;
    checkpoint_date: Date | null;
    status: string;
    attempts: number;
    last_error: string | null;
    created_at: Date;
    updated_at: Date;
};

export type CreditDashboardDailySnapshot = {
    id: bigint;
    account_id: number;
    policy_id: number | null;
    business_unit_id: number | null;
    snapshot_date: Date;
    health_index: number;
    total_receivables: number;
    compliant_exposure: number;
    at_risk_exposure: number;
    policy_risk_exposure: number;
    policy_risk_exposure_customer_count: number;
    gross_risk_exposure: number;
    overdue_block_customer_count: number;
    overdue_block_total_outstanding: number;
    capacity_gap_total_amount: number;
    capacity_gap_customer_over_limit_count: number;
    terms_breach_invoice_count: number;
    terms_breach_total_amount: number;
    terms_breach_count_by_reason: JsonValue;
    without_policy_customer_count: number;
    without_policy_total_amount: number;
    reporting_countdown_invoice_count: number;
    reporting_countdown_total_amount: number;
    reporting_countdown_window_days: number;
    limit_warnings_customer_count: number;
    limit_warnings_total_amount: number;
    limit_warnings_threshold_pct: number;
    limit_warnings_score_warn_days: number;
    account_currency: string;
    top_up_cover_total_amount: number | null;
    customers_with_active_top_up_count: number | null;
    top_up_expiring_customer_count: number | null;
    created_at: Date;
    modified_at: Date;
};

export type CreditDashboardDailySnapshotRelations = {
    BusinessUnit: BusinessUnit | null;
};

export type CronJob = {
    id: number;
    created_at: Date;
    name: string;
    active: boolean | null;
    cron_expression: string;
    last_run_at: Date | null;
    next_run_at: Date | null;
    modified_at: Date;
    sort_order: number;
    timeout_period_seconds: number;
    last_execution_duration_seconds: number | null;
    average_execution_duration_seconds: number | null;
    min_execution_duration_seconds: number | null;
    max_execution_duration_seconds: number | null;
    success_count_30d: number;
    failure_count_30d: number;
    timeout_count_30d: number;
    last_success_at: Date | null;
    last_failure_at: Date | null;
    last_timeout_at: Date | null;
    performance_baseline_seconds: number | null;
    performance_degradation_alert_sent_at: Date | null;
    alert_duration_threshold_seconds: number | null;
    alert_failure_rate_threshold: Decimal | null;
    alert_connection_threshold: number | null;
    alert_enabled: boolean;
};

export type CronJobRelations = {
    Log: Log[];
};

export type CurrencyRate = {
    id: number;
    rate_date: Date;
    base_currency: string;
    other_currency: string;
    currency_ratio: number;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type Customer = {
    id: number;
    account_id: number;
    created_at: Date;
    customer_number: string | null;
    crn: string | null;
    country_id: number | null;
    address_line1: string | null;
    address_line2: string | null;
    postal_code: string | null;
    modified_at: Date;
    type: client_type;
    phone: string | null;
    email: string | null;
    city: string | null;
    state_id: number | null;
    total_invoices_overdue: number | null;
    number_of_overdue_invoices: number | null;
    collection_status: record_status;
    company_id: number | null;
    person_id: number | null;
    customer_uuid: string;
    owner_id: string | null;
    language: language;
    first_activity_delay_days: number | null;
    category_for_new_collection: category | null;
    total_due_amount: number | null;
    no_of_due_invoices: number | null;
    customer_due_amount1: number | null;
    customer_due_currency1: string | null;
    customer_due_amount2: number | null;
    customer_due_currency2: string | null;
    total_overdue_amount: number | null;
    customer_overdue_amount1: number | null;
    customer_overdue_currency1: string | null;
    customer_overdue_amount2: number | null;
    customer_overdue_currency2: string | null;
    sequence_container_id: number | null;
    business_unit_id: number | null;
    created_by: string | null;
    modified_by: string | null;
    parent_customer_id: number | null;
    generic_text1: string | null;
    generic_text2: string | null;
    generic_number1: number | null;
    generic_number2: number | null;
    generic_date1: Date | null;
    generic_date2: Date | null;
    automation_stuck_no_contacts: boolean | null;
    oldest_invoice_overdue_date: Date | null;
    overdue_block: boolean;
    zero_limit_alert_exist: boolean;
};

export type CustomerRelations = {
    Activity: Activity[];
    CommunicationChannelPreference: CommunicationChannelPreference[];
    CommunicationLearningData: CommunicationLearningData[];
    Contact: Contact[];
    Account: Account;
    Person: Person | null;
    Company: Company | null;
    Owner: User | null;
    BusinessUnit: BusinessUnit | null;
    Country: Country | null;
    State: State | null;
    User_Customer_created_byToUser: User | null;
    User_Customer_modified_byToUser: User | null;
    ParentCustomer: Customer | null;
    ChildCustomers: Customer[];
    SequenceContainer: SequenceContainer | null;
    CustomerBanks: CustomerBanks[];
    CustomerCollectionPeriod: CustomerCollectionPeriod[];
    CustomerDispute: CustomerDispute[];
    Invoice: Invoice[];
    InvoicePayment: InvoicePayment[];
    Payment: Payment[];
    CustomerAggregatedData: CustomerAggregatedData | null;
    CustomerPolicy: CustomerPolicy[];
    CustomerPolicyTrend: CustomerPolicyTrend[];
    CustomerTopUp: CustomerTopUp[];
    CustomerCheckpoint: CustomerCheckpoint | null;
};

export type CustomerAggregatedData = {
    id: number;
    customer_id: number;
    created_at: Date;
    modified_at: Date;
    total_outstanding_amount: number | null;
    customer_outstanding_amount1: number | null;
    customer_outstanding_amount2: number | null;
    customer_currency1: string | null;
    customer_currency2: string | null;
    no_of_overdue_invoices: number | null;
    no_of_due_invoices: number | null;
    total_invoices_count: number | null;
    total_paid_amount: number | null;
    customer_total_paid_amount1: number | null;
    customer_total_paid_amount2: number | null;
    total_collection_periods: number | null;
    active_collection_periods: number | null;
    child_customers_count: number | null;
    created_by: string | null;
    modified_by: string | null;
};

export type CustomerAggregatedDataRelations = {
    Customer: Customer;
    User_CustomerAggregatedData_created_byToUser: User | null;
    User_CustomerAggregatedData_modified_byToUser: User | null;
};

export type CustomerBanks = {
    id: number;
    customer_id: number;
    account_id: number;
    customer_bank_account_id: number;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type CustomerBanksRelations = {
    User_CustomerBanks_created_byToUser: User | null;
    User_CustomerBanks_modified_byToUser: User | null;
    Account: Account;
    Customer: Customer;
    AccountBankAccounts: AccountBankAccounts;
};

export type CustomerCheckpoint = {
    id: number;
    customer_id: number;
    account_id: number;
    payload: JsonValue;
    saved_at: Date;
    saved_by: string | null;
    created_at: Date;
    modified_at: Date;
};

export type CustomerCheckpointRelations = {
    Customer: Customer;
    Account: Account;
};

export type CustomerCollectionPeriod = {
    id: number;
    created_at: Date;
    modified_at: Date;
    customer_id: number;
    period_start_date: Date;
    period_end_date: Date | null;
    last_automated_step: number | null;
    previous_category: category | null;
    current_category: category | null;
    priority: priority | null;
    total_outstanding_amount: number | null;
    no_of_overdue_invoices: number | null;
    currency: string | null;
    promise_to_pay_date: Date | null;
    last_dispute_date: Date | null;
    customer_outstanding_amount1: number | null;
    customer_outstanding_amount2: number | null;
    customer_currency1: string | null;
    customer_currency2: string | null;
    last_call: Date | null;
    last_call_result: string | null;
    follow_up_time: Date | null;
    promise_to_pay_amount: number | null;
    next_category: category | null;
    next_category_date: Date | null;
    create_next_activity: boolean;
    next_activity_date: Date | null;
    promise_to_pay_count: number;
    is_last_automated_step_delivered: boolean;
    risk_score: Decimal | null;
    risk_factors: JsonValue | null;
    last_risk_calculation: Date | null;
    risk_category: string | null;
    lawyer_assigned: boolean;
    created_by: string | null;
    modified_by: string | null;
};

export type CustomerCollectionPeriodRelations = {
    Activity: Activity[];
    User_CustomerCollectionPeriod_created_byToUser: User | null;
    User_CustomerCollectionPeriod_modified_byToUser: User | null;
    Customer: Customer;
    CustomerDispute: CustomerDispute[];
    Invoice: Invoice[];
};

export type CustomerDispute = {
    id: number;
    created_at: Date;
    modified_at: Date;
    customer_id: number;
    dispute_reason_id: number | null;
    dispute_status: dispute_status | null;
    owner_id: string | null;
    dispute_resolution: dispute_resolution | null;
    customer_comment: string | null;
    customer_collection_period_id: number | null;
    resolution_comment: string | null;
    invoices_in_dispute: string | null;
    contact_first_name: string | null;
    contact_last_name: string | null;
    contact_email: string | null;
    contact_mobile: string | null;
    created_by: string | null;
    modified_by: string | null;
    closed_at: Date | null;
};

export type CustomerDisputeRelations = {
    User_CustomerDispute_created_byToUser: User | null;
    User_CustomerDispute_modified_byToUser: User | null;
    CustomerCollectionPeriod: CustomerCollectionPeriod | null;
    Customer: Customer;
    DisputeReason: DisputeReason | null;
    User_CustomerDispute_owner_idToUser: User | null;
    DisputeInvoice: DisputeInvoice[];
};

export type CustomerPolicy = {
    id: number;
    created_at: Date;
    modified_at: Date;
    customer_id: number;
    insurance_policy_id: number | null;
    customer_number_policy: string | null;
    approved_limit: Decimal | null;
    approved_limit_currency: string | null;
    approved_limit_expiration_date: Date | null;
    zero_limit_date: Date | null;
    limit_type: customer_limit_type | null;
    max_payment_term: number | null;
    max_allowed_mep: number | null;
    reporting_days: number | null;
    mep_cutoff_day_of_month: number | null;
    mep_substitute_day_of_month: number | null;
    reporting_cutoff_day_of_month: number | null;
    reporting_substitute_day_of_month: number | null;
    payment_term_cutoff_day_of_month: number | null;
    payment_term_substitute_day_of_month: number | null;
    excluded_from_policy: boolean;
    policy_exclusion_reason: string | null;
    credit_score: Decimal | null;
    credit_score_input_date: Date | null;
    active_customer_since: Date | null;
    outdated_dcl: boolean;
    is_active: boolean;
    capacity_gap_amount: number | null;
    capacity_gap_amount_date: Date | null;
    retained_capacity_gap: number | null;
    uninsured_amount: number | null;
    capacity_gap_amount1: number | null;
    capacity_gap_currency1: string | null;
    capacity_gap_amount2: number | null;
    capacity_gap_currency2: string | null;
    uninsured_amount1: number | null;
    uninsured_currency1: string | null;
    uninsured_amount2: number | null;
    uninsured_currency2: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type CustomerPolicyRelations = {
    Customer: Customer;
    InsurancePolicy: InsurancePolicy | null;
    User_CustomerPolicy_created_byToUser: User | null;
    User_CustomerPolicy_modified_byToUser: User | null;
    CustomerPolicyTrend: CustomerPolicyTrend[];
};

export type CustomerPolicyTrend = {
    id: bigint;
    account_id: number;
    customer_id: number;
    insurance_policy_id: number | null;
    customer_policy_id: number | null;
    snapshot_date: Date;
    approved_limit: Decimal | null;
    usage_amount: number;
    usage_pct: number | null;
    customer_number_policy: string | null;
    approved_limit_currency: string | null;
    approved_limit_expiration_date: Date | null;
    limit_type: customer_limit_type | null;
    max_payment_term: number | null;
    max_allowed_mep: number | null;
    reporting_days: number | null;
    mep_cutoff_day_of_month: number | null;
    mep_substitute_day_of_month: number | null;
    reporting_cutoff_day_of_month: number | null;
    reporting_substitute_day_of_month: number | null;
    payment_term_cutoff_day_of_month: number | null;
    payment_term_substitute_day_of_month: number | null;
    excluded_from_policy: boolean;
    policy_exclusion_reason: string | null;
    credit_score: Decimal | null;
    credit_score_input_date: Date | null;
    active_customer_since: Date | null;
    outdated_dcl: boolean;
    top_up_total: number | null;
    effective_approved_limit: Decimal | null;
    active_top_up_count: number | null;
    policy_daily_cost: Decimal | null;
    policy_cost_currency: string | null;
    top_up_daily_cost: Decimal | null;
    top_up_cost_currency: string | null;
    total_daily_cost: Decimal | null;
    cost_calculation_method: cost_calculation_method | null;
    cost_percent: Decimal | null;
    financial_currency: string | null;
    total_receivables: Decimal | null;
    health_index: number | null;
    at_risk_exposure: Decimal | null;
    compliant_exposure: Decimal | null;
    terms_breach_amount: Decimal | null;
    capacity_gap_amount: Decimal | null;
    terms_breach_count: number | null;
    terms_breach_by_reason: JsonValue;
    policy_usage_pct: number | null;
    top_up_usage_pct: number | null;
    effective_usage_pct: number | null;
    created_at: Date;
    modified_at: Date;
};

export type CustomerPolicyTrendRelations = {
    Customer: Customer;
    InsurancePolicy: InsurancePolicy | null;
    CustomerPolicy: CustomerPolicy | null;
};

export type CustomerTopUp = {
    id: number;
    customer_id: number;
    insurance_policy_id: number;
    top_up_type: customer_top_up_type;
    top_up_value: Decimal;
    currency: string | null;
    start_date: Date;
    end_date: Date;
    notes: string | null;
    premium: Decimal | null;
    premium_currency: string | null;
    cancelled_at: Date | null;
    created_by: string | null;
    modified_by: string | null;
    created_at: Date;
    modified_at: Date;
};

export type CustomerTopUpRelations = {
    Customer: Customer;
    InsurancePolicy: InsurancePolicy;
    User_CustomerTopUp_created_byToUser: User | null;
    User_CustomerTopUp_modified_byToUser: User | null;
};

export type DashboardCache = {
    id: number;
    account_id: number;
    business_unit_id: number | null;
    owner_id: string | null;
    view_mode: string;
    cache_key: string;
    active_customers: number;
    overdue_amount: number;
    overdue_invoices: number;
    total_collected: number;
    total_due: number;
    due_today: number;
    due_this_week: number;
    due_this_month: number;
    due_next_month: number;
    collection_stats: JsonValue | null;
    category_stats: JsonValue | null;
    dispute_stats: JsonValue | null;
    chart_data: JsonValue | null;
    aging_portfolio: JsonValue | null;
    receivables_schedule: JsonValue | null;
    invoices_by_customer: JsonValue | null;
    invoices_by_business_unit: JsonValue | null;
    overdue_invoices_by_customer: JsonValue | null;
    overdue_invoices_by_business_unit: JsonValue | null;
    last_calculated_at: Date;
    expires_at: Date;
    created_at: Date;
    modified_at: Date;
};

export type DisputeInvoice = {
    id: number;
    dispute_id: number;
    invoice_id: number;
    created_at: Date | null;
    modified_at: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type DisputeInvoiceRelations = {
    User_DisputeInvoice_created_byToUser: User | null;
    User_DisputeInvoice_modified_byToUser: User | null;
    CustomerDispute: CustomerDispute;
    Invoice: Invoice;
};

export type DisputeReason = {
    id: number;
    created_at: Date;
    modified_at: Date;
    account_id: number | null;
    master_template: boolean;
    name: string;
    status: record_status;
    editable: boolean | null;
    created_by: string | null;
    modified_by: string | null;
};

export type DisputeReasonRelations = {
    CustomerDispute: CustomerDispute[];
    User_DisputeReason_created_byToUser: User | null;
    User_DisputeReason_modified_byToUser: User | null;
    Account: Account | null;
    DisputeReasonLanguage: DisputeReasonLanguage[];
};

export type DisputeReasonLanguage = {
    id: number;
    created_at: Date;
    modified_at: Date;
    dispute_reason_id: number;
    language: string;
    name: string;
    created_by: string | null;
    modified_by: string | null;
};

export type DisputeReasonLanguageRelations = {
    User_DisputeReasonLanguage_created_byToUser: User | null;
    User_DisputeReasonLanguage_modified_byToUser: User | null;
    DisputeReason: DisputeReason;
};

export type ImportJob = {
    id: string;
    created_at: Date;
    modified_at: Date;
    account_id: number;
    user_id: string | null;
    import_type: ImportType;
    status: ImportStatus;
    total_records: number;
    processed_records: number;
    successful_records: number;
    failed_records: number;
    started_at: Date | null;
    completed_at: Date | null;
    error_message: string | null;
    metadata: JsonValue | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ImportJobRelations = {
    User_ImportJob_created_byToUser: User | null;
    User_ImportJob_modified_byToUser: User | null;
    Account: Account;
    User_ImportJob_user_idToUser: User | null;
    ImportRecord: ImportRecord[];
};

export type ImportRecord = {
    id: string;
    created_at: Date;
    modified_at: Date;
    import_job_id: string;
    row_index: number;
    status: ImportRecordStatus;
    original_data: JsonValue;
    processed_data: JsonValue | null;
    validation_errors: JsonValue | null;
    processing_errors: JsonValue | null;
    result_message: string | null;
    entity_id: number | null;
    created_by: string | null;
    modified_by: string | null;
};

export type ImportRecordRelations = {
    User_ImportRecord_created_byToUser: User | null;
    User_ImportRecord_modified_byToUser: User | null;
    ImportJob: ImportJob;
};

export type InsurancePolicy = {
    id: number;
    created_at: Date;
    modified_at: Date;
    account_id: number;
    policy_number: string;
    start_date: Date;
    end_date: Date;
    currency: string | null;
    insurer_name: string | null;
    policy_kind: insurance_policy_kind;
    parent_insurance_policy_id: number | null;
    allow_concurrent_top_ups: boolean;
    max_total_cover: Decimal | null;
    max_total_dcl_sdl_cover: Decimal | null;
    min_credit_score: Decimal | null;
    score_validity_period_months: number | null;
    max_dcl: Decimal | null;
    dcl_customer_since_months: number | null;
    max_payment_term: number | null;
    max_allowed_mep: number | null;
    reporting_days: number | null;
    mep_cutoff_day_of_month: number | null;
    mep_substitute_day_of_month: number | null;
    reporting_cutoff_day_of_month: number | null;
    reporting_substitute_day_of_month: number | null;
    payment_term_cutoff_day_of_month: number | null;
    payment_term_substitute_day_of_month: number | null;
    cost_calculation_method: cost_calculation_method | null;
    cost_percent: Decimal | null;
    status: record_status;
    auto_activate_on_term_start: boolean;
    created_by: string | null;
    modified_by: string | null;
};

export type InsurancePolicyRelations = {
    Account: Account;
    User_InsurancePolicy_created_byToUser: User | null;
    User_InsurancePolicy_modified_byToUser: User | null;
    InsurancePolicyCountry: InsurancePolicyCountry[];
    NamedPolicy: NamedPolicy[];
    CustomerPolicy: CustomerPolicy[];
    CustomerPolicyTrend: CustomerPolicyTrend[];
    InsurancePolicyTrend: InsurancePolicyTrend[];
    InsurancePolicyCountryTrend: InsurancePolicyCountryTrend[];
    NamedPolicyTrend: NamedPolicyTrend[];
    Invoice: Invoice[];
    CustomerTopUp: CustomerTopUp[];
    ParentInsurancePolicy: InsurancePolicy | null;
    ChildInsurancePolicies: InsurancePolicy[];
};

export type InsurancePolicyCountry = {
    id: string;
    created_at: Date;
    modified_at: Date;
    insurance_policy_id: number;
    country_id: number;
    payment_term_cap: number | null;
    country_mep: number | null;
    reporting_days: number | null;
    country_max_limit: Decimal | null;
    created_by: string | null;
    modified_by: string | null;
};

export type InsurancePolicyCountryRelations = {
    InsurancePolicy: InsurancePolicy;
    Country: Country;
    User_InsurancePolicyCountry_created_byToUser: User | null;
    User_InsurancePolicyCountry_modified_byToUser: User | null;
    InsurancePolicyCountryTrend: InsurancePolicyCountryTrend[];
};

export type InsurancePolicyCountryTrend = {
    id: bigint;
    account_id: number;
    insurance_policy_id: number;
    insurance_policy_country_id: string;
    country_id: number;
    snapshot_date: Date;
    payment_term_cap: number | null;
    country_mep: number | null;
    reporting_days: number | null;
    country_max_limit: Decimal | null;
    created_at: Date;
    modified_at: Date;
};

export type InsurancePolicyCountryTrendRelations = {
    InsurancePolicyCountry: InsurancePolicyCountry;
    InsurancePolicy: InsurancePolicy;
};

export type InsurancePolicyTrend = {
    id: bigint;
    account_id: number;
    insurance_policy_id: number;
    snapshot_date: Date;
    policy_number: string;
    start_date: Date;
    end_date: Date;
    currency: string | null;
    insurer_name: string | null;
    policy_kind: insurance_policy_kind;
    parent_insurance_policy_id: number | null;
    allow_concurrent_top_ups: boolean;
    max_total_cover: Decimal | null;
    max_total_dcl_sdl_cover: Decimal | null;
    min_credit_score: Decimal | null;
    score_validity_period_months: number | null;
    max_dcl: Decimal | null;
    dcl_customer_since_months: number | null;
    max_payment_term: number | null;
    max_allowed_mep: number | null;
    reporting_days: number | null;
    cost_calculation_method: cost_calculation_method | null;
    cost_percent: Decimal | null;
    status: record_status;
    active_customer_count: number;
    total_approved_limit: Decimal | null;
    total_open_ar: number;
    policy_usage_pct: number | null;
    named_policy_row_count: number;
    country_row_count: number;
    created_at: Date;
    modified_at: Date;
};

export type InsurancePolicyTrendRelations = {
    InsurancePolicy: InsurancePolicy;
};

export type InternalEmailTemplate = {
    id: number;
    created_at: Date;
    modified_at: Date;
    name: string;
    type: internal_email_template_type;
    subject: string;
    content: string;
    active: boolean;
    account_id: number;
    master_template: boolean;
    created_by: string | null;
    modified_by: string | null;
};

export type InternalEmailTemplateRelations = {
    User_InternalEmailTemplate_created_byToUser: User | null;
    User_InternalEmailTemplate_modified_byToUser: User | null;
    Account: Account;
};

export type Invoice = {
    id: number;
    created_at: Date;
    promise_to_pay: number | null;
    modified_at: Date;
    customer_id: number | null;
    policy_id: number | null;
    invoice_number: string | null;
    amount: number | null;
    due_date: Date | null;
    oldest_overdue_invoice_date: Date | null;
    total_paid: number | null;
    status: invoice_status;
    last_payment_date: Date | null;
    zero_limit_alert: boolean;
    invoice_date: Date;
    outstanding_debt: number | null;
    collection_period_id: number | null;
    first_activity_date: Date | null;
    customer_number: number | null;
    account_id: number;
    customer_total_paid: number | null;
    customer_amount: number | null;
    customer_outstanding_debt: number | null;
    customer_currency: string | null;
    credit_for_invoice_id: number | null;
    net_amount: number | null;
    credit_for_invoice_number: string | null;
    customer_net_amount: number | null;
    generic_text1: string | null;
    generic_text2: string | null;
    generic_number1: number | null;
    generic_number2: number | null;
    generic_date1: Date | null;
    generic_date2: Date | null;
    created_by: string | null;
    modified_by: string | null;
    due_notification_state: JsonValue | null;
    payment_term: number | null;
    target_reporting_date: Date | null;
    actual_reporting_date: Date | null;
    reporting_comment: string | null;
    reporting_captured_at: Date | null;
    target_mep_date: Date | null;
    reported_status: invoice_reported_status | null;
    reporting_breach: boolean;
    ctv_payment_term: boolean;
    ctv_customer_overdue_mep: boolean;
    ctv_customer_excluded_from_policy: boolean;
    ctv_outdated_dcl: boolean;
    ctv_invoice_after_policy_end: boolean;
    in_capacity_gap: boolean;
    limit_assessed_amount: Decimal | null;
    limit_assessed_at: Date | null;
    limit_assessed_currency: string | null;
    capacity_gap_amount: Decimal | null;
    capacity_gap_amount_limit: Decimal | null;
    capacity_gap_amount_date: Date | null;
};

export type InvoiceRelations = {
    DisputeInvoice: DisputeInvoice[];
    User_Invoice_created_byToUser: User | null;
    User_Invoice_modified_byToUser: User | null;
    Account: Account;
    CustomerCollectionPeriod: CustomerCollectionPeriod | null;
    Invoice: Invoice | null;
    other_Invoice: Invoice[];
    Customer: Customer | null;
    InsurancePolicy: InsurancePolicy | null;
    InvoicePayment: InvoicePayment[];
    Activity: Activity[];
};

export type InvoicePayment = {
    id: number;
    invoice_id: number | null;
    customer_currency: string;
    payment_date: Date;
    amount: number;
    payment_method: string;
    reference: string;
    customer_id: number;
    account_id: number;
    customer_amount: number;
    invoice_number: string | null;
    created_at: Date | null;
    modified_at: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type InvoicePaymentRelations = {
    User_InvoicePayment_created_byToUser: User | null;
    User_InvoicePayment_modified_byToUser: User | null;
    Customer: Customer;
    Invoice: Invoice | null;
    Account: Account;
};

export type Log = {
    id: bigint;
    timestamp: Date;
    level: log_level;
    message: string;
    source: string;
    details: JsonValue | null;
    account_id: number | null;
    user_id: string | null;
    job_id: number | null;
    correlation_id: string | null;
    sub_source: string | null;
};

export type LogRelations = {
    Account: Account | null;
    CronJob: CronJob | null;
    User: User | null;
};

export type NamedPolicy = {
    id: number;
    created_at: Date;
    modified_at: Date;
    insurance_policy_id: number;
    customer_number: string;
    max_payment_term: number | null;
    customer_mep: number | null;
    reporting_days: number | null;
    customer_max_limit: Decimal | null;
    limit_expiration_date: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type NamedPolicyRelations = {
    InsurancePolicy: InsurancePolicy;
    User_NamedPolicy_created_byToUser: User | null;
    User_NamedPolicy_modified_byToUser: User | null;
    NamedPolicyTrend: NamedPolicyTrend[];
};

export type NamedPolicyTrend = {
    id: bigint;
    account_id: number;
    insurance_policy_id: number;
    named_policy_id: number;
    snapshot_date: Date;
    customer_number: string;
    max_payment_term: number | null;
    customer_mep: number | null;
    reporting_days: number | null;
    customer_max_limit: Decimal | null;
    limit_expiration_date: Date | null;
    created_at: Date;
    modified_at: Date;
};

export type NamedPolicyTrendRelations = {
    NamedPolicy: NamedPolicy;
    InsurancePolicy: InsurancePolicy;
};

export type Notification = {
    id: string;
    created_at: Date;
    modified_at: Date;
    type: notification_type;
    title: string;
    message: string;
    priority: priority;
    user_id: string;
    account_id: number;
    read: boolean;
    action_url: string | null;
    metadata: JsonValue | null;
    created_by: string | null;
    modified_by: string | null;
};

export type NotificationRelations = {
    User_Notification_created_byToUser: User | null;
    User_Notification_modified_byToUser: User | null;
    Account: Account;
    User_Notification_user_idToUser: User;
};

export type NotificationDeliveryLog = {
    id: bigint;
    account_id: number;
    rule_id: number;
    entity_type: string;
    entity_id: string;
    offset_days: number | null;
    channel: notification_delivery_channel;
    delivered_at: Date;
    cleared_at: Date | null;
    metadata: JsonValue | null;
    created_at: Date;
    modified_at: Date;
};

export type NotificationDeliveryLogRelations = {
    Account: Account;
    rule: NotificationRule;
};

export type NotificationRule = {
    id: number;
    rule_set_id: number;
    advance_day_offsets: number[];
    metadata: JsonValue | null;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type NotificationRuleRelations = {
    rule_set: NotificationRuleSet;
    role_defaults: NotificationRuleRoleDefault[];
    user_overrides: NotificationRuleUserOverride[];
    delivery_logs: NotificationDeliveryLog[];
};

export type NotificationRuleRoleDefault = {
    id: number;
    rule_id: number;
    role: user_role;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type NotificationRuleRoleDefaultRelations = {
    rule: NotificationRule;
};

export type NotificationRuleSet = {
    id: number;
    account_id: number;
    product: notification_rule_product;
    trigger_type: notification_rule_trigger_type;
    enabled: boolean;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type NotificationRuleSetRelations = {
    Account: Account;
    rules: NotificationRule[];
};

export type NotificationRuleUserOverride = {
    id: number;
    rule_id: number;
    user_id: string;
    active: boolean;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type NotificationRuleUserOverrideRelations = {
    rule: NotificationRule;
};

export type Payment = {
    id: number;
    created_at: Date;
    payment_date: Date;
    amount: number;
    payment_method: string | null;
    reference: string | null;
    customer_id: number;
    account_id: number;
    customer_amount: number | null;
    customer_currency: string | null;
    generic_text1: string | null;
    generic_text2: string | null;
    generic_number1: number | null;
    generic_number2: number | null;
    generic_date1: Date | null;
    generic_date2: Date | null;
    created_by: string | null;
    modified_by: string | null;
};

export type PaymentRelations = {
    User_Payment_created_byToUser: User | null;
    User_Payment_modified_byToUser: User | null;
    Account: Account;
    Customer: Customer;
};

export type Person = {
    id: number;
    created_at: Date;
    modified_at: Date;
    first_name: string | null;
    last_name: string | null;
    date_of_birth: Date | null;
    identification_number: string | null;
    mobile: string | null;
    full_name: string | null;
    created_by: string | null;
    modified_by: string | null;
};

export type PersonRelations = {
    User_Person_created_byToUser: User | null;
    User_Person_modified_byToUser: User | null;
    Customer: Customer[];
};

export type Report = {
    id: number;
    account_id: number;
    name: string;
    unique_name: string;
    description: string | null;
    report_config: JsonValue;
    is_public: boolean;
    is_system: boolean;
    is_default: boolean;
    context: string | null;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type ReportRelations = {
    Account: Account;
    User_Report_created_byToUser: User | null;
    User_Report_modified_byToUser: User | null;
    ReportShare: ReportShare[];
    ReportSchedule: ReportSchedule[];
    ReportExecution: ReportExecution[];
    UserDefaultReport: UserDefaultReport[];
};

export type ReportExecution = {
    id: number;
    report_id: number;
    executed_by: string | null;
    executed_at: Date;
    execution_config: JsonValue | null;
    result_count: number | null;
    execution_time_ms: number | null;
};

export type ReportExecutionRelations = {
    Report: Report;
    User_ReportExecution_executed_byToUser: User | null;
};

export type ReportSchedule = {
    id: number;
    report_id: number;
    schedule_type: string;
    schedule_config: JsonValue;
    is_active: boolean;
    last_run_at: Date | null;
    next_run_at: Date | null;
    created_at: Date;
    modified_at: Date;
};

export type ReportScheduleRelations = {
    Report: Report;
};

export type ReportShare = {
    id: number;
    report_id: number;
    shared_with_user_id: string | null;
    shared_with_role: user_role | null;
    permission: string;
    created_at: Date;
    created_by: string | null;
};

export type ReportShareRelations = {
    Report: Report;
    User_ReportShare_shared_with_user_idToUser: User | null;
    User_ReportShare_created_byToUser: User | null;
};

export type RolePermission = {
    id: number;
    account_id: number;
    role: user_role;
    permission_key: string;
    is_collection: boolean;
    is_credit_insurance: boolean;
    created_at: Date;
    modified_at: Date;
    created_by: string | null;
    modified_by: string | null;
};

export type RolePermissionRelations = {
    Account: Account;
    User_RolePermission_created_byToUser: User | null;
    User_RolePermission_modified_byToUser: User | null;
};

export type SequenceContainer = {
    id: number;
    created_at: Date;
    modified_at: Date;
    name: string;
    category: category;
    account_id: number;
    is_default: boolean;
    active: boolean;
    master_template: boolean;
    is_deleted: boolean;
    created_by: string | null;
    modified_by: string | null;
};

export type SequenceContainerRelations = {
    ActivitiesSequence: ActivitiesSequence[];
    Customer: Customer[];
    User_SequenceContainer_created_byToUser: User | null;
    User_SequenceContainer_modified_byToUser: User | null;
    Account: Account;
};

export type Session = {
    id: string;
    userId: string;
    expires: Date;
    sessionToken: string;
    created_at: Date;
    modified_at: Date;
};

export type SessionRelations = {
    User: User;
};

export type SMSVendor = {
    id: number;
    name: string;
    provider: string;
    api_key: string | null;
    api_secret: string | null;
    account_sid: string | null;
    auth_token: string | null;
    webhook_url: string | null;
    is_active: boolean | null;
    priority: number | null;
    cost_per_sms: Decimal | null;
    currency: string | null;
    created_at: Date | null;
    modified_at: Date | null;
    use_account_sender_name: boolean | null;
    created_by: string | null;
    modified_by: string | null;
};

export type SMSVendorRelations = {
    AccountSMSProviderPreferences: AccountSMSProviderPreferences[];
    ActivityContact: ActivityContact[];
    CountrySMSVendor: CountrySMSVendor[];
    User_SMSVendor_created_byToUser: User | null;
    User_SMSVendor_modified_byToUser: User | null;
};

export type State = {
    id: number;
    name: string;
    country_id: number;
    country_code: string;
    fips_code: string | null;
    iso2: string | null;
    type: string | null;
    level: number | null;
    parent_id: number | null;
    latitude: Decimal | null;
    longitude: Decimal | null;
    created_at: Date | null;
    modified_at: Date;
    flag: number;
    wikiDataId: string | null;
};

export type StateRelations = {
    Account: Account[];
    AccountBankAccounts: AccountBankAccounts[];
    Contact: Contact[];
    Country: Country;
    Customer: Customer[];
};

export type User = {
    id: string;
    name: string | null;
    email: string;
    username: string;
    emailVerified: Date | null;
    image: string | null;
    created_at: Date;
    modified_at: Date;
    language: language;
    account_id: number | null;
    password: string | null;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
    status: record_status;
    first_name: string | null;
    last_name: string | null;
    role: user_role | null;
    mobile: string | null;
    time_zone: string | null;
    currency: string | null;
    locale: string | null;
    session_version: number;
    freeze: boolean;
    sidebar_collapsed: boolean | null;
    failed_login_attempts: number;
    last_failed_login_at: Date | null;
    deactivated_at: Date | null;
    guided_tooltips_enabled: boolean | null;
    is_audit_user: boolean;
    created_by: string | null;
    modified_by: string | null;
    business_unit_id: number | null;
};

export type UserRelations = {
    Account_Account_created_byToUser: Account[];
    Account_Account_modified_byToUser: Account[];
    Account_Account_deleted_byToUser: Account[];
    AccountBankAccounts_AccountBankAccounts_created_byToUser: AccountBankAccounts[];
    AccountBankAccounts_AccountBankAccounts_modified_byToUser: AccountBankAccounts[];
    AccountSMSProviderPreferences_AccountSMSProviderPreferences_created_byToUser: AccountSMSProviderPreferences[];
    AccountSMSProviderPreferences_AccountSMSProviderPreferences_modified_byToUser: AccountSMSProviderPreferences[];
    ActivitiesSequence_ActivitiesSequence_created_byToUser: ActivitiesSequence[];
    ActivitiesSequence_ActivitiesSequence_modified_byToUser: ActivitiesSequence[];
    ActivitiesTemplate_ActivitiesTemplate_created_byToUser: ActivitiesTemplate[];
    ActivitiesTemplate_ActivitiesTemplate_modified_byToUser: ActivitiesTemplate[];
    Activity_Activity_created_byToUser: Activity[];
    Activity_Activity_modified_byToUser: Activity[];
    ActivityAttachment_ActivityAttachment_created_byToUser: ActivityAttachment[];
    ActivityAttachment_ActivityAttachment_modified_byToUser: ActivityAttachment[];
    ActivityContact_ActivityContact_created_byToUser: ActivityContact[];
    ActivityContact_ActivityContact_modified_byToUser: ActivityContact[];
    ActivityTemplateLanguage_ActivityTemplateLanguage_created_byToUser: ActivityTemplateLanguage[];
    ActivityTemplateLanguage_ActivityTemplateLanguage_modified_byToUser: ActivityTemplateLanguage[];
    CommunicationChannelPreference_CommunicationChannelPreference_created_byToUser: CommunicationChannelPreference[];
    CommunicationChannelPreference_CommunicationChannelPreference_modified_byToUser: CommunicationChannelPreference[];
    CommunicationLearningData_CommunicationLearningData_created_byToUser: CommunicationLearningData[];
    CommunicationLearningData_CommunicationLearningData_modified_byToUser: CommunicationLearningData[];
    Company_Company_created_byToUser: Company[];
    Company_Company_modified_byToUser: Company[];
    Contact_Contact_created_byToUser: Contact[];
    Contact_Contact_modified_byToUser: Contact[];
    CountrySMSVendor_CountrySMSVendor_created_byToUser: CountrySMSVendor[];
    CountrySMSVendor_CountrySMSVendor_modified_byToUser: CountrySMSVendor[];
    Customer_Customer_created_byToUser: Customer[];
    Customer_Customer_modified_byToUser: Customer[];
    CustomerPolicy_CustomerPolicy_created_byToUser: CustomerPolicy[];
    CustomerPolicy_CustomerPolicy_modified_byToUser: CustomerPolicy[];
    Customer_Customer_owner_idToUser: Customer[];
    CustomerBanks_CustomerBanks_created_byToUser: CustomerBanks[];
    CustomerBanks_CustomerBanks_modified_byToUser: CustomerBanks[];
    CustomerCollectionPeriod_CustomerCollectionPeriod_created_byToUser: CustomerCollectionPeriod[];
    CustomerCollectionPeriod_CustomerCollectionPeriod_modified_byToUser: CustomerCollectionPeriod[];
    CustomerAggregatedData_CustomerAggregatedData_created_byToUser: CustomerAggregatedData[];
    CustomerAggregatedData_CustomerAggregatedData_modified_byToUser: CustomerAggregatedData[];
    CustomerDispute_CustomerDispute_created_byToUser: CustomerDispute[];
    CustomerDispute_CustomerDispute_modified_byToUser: CustomerDispute[];
    CustomerDispute_CustomerDispute_owner_idToUser: CustomerDispute[];
    DisputeInvoice_DisputeInvoice_created_byToUser: DisputeInvoice[];
    DisputeInvoice_DisputeInvoice_modified_byToUser: DisputeInvoice[];
    DisputeReason_DisputeReason_created_byToUser: DisputeReason[];
    DisputeReason_DisputeReason_modified_byToUser: DisputeReason[];
    DisputeReasonLanguage_DisputeReasonLanguage_created_byToUser: DisputeReasonLanguage[];
    DisputeReasonLanguage_DisputeReasonLanguage_modified_byToUser: DisputeReasonLanguage[];
    ImportJob_ImportJob_created_byToUser: ImportJob[];
    ImportJob_ImportJob_modified_byToUser: ImportJob[];
    ImportJob_ImportJob_user_idToUser: ImportJob[];
    ImportRecord_ImportRecord_created_byToUser: ImportRecord[];
    ImportRecord_ImportRecord_modified_byToUser: ImportRecord[];
    InternalEmailTemplate_InternalEmailTemplate_created_byToUser: InternalEmailTemplate[];
    InternalEmailTemplate_InternalEmailTemplate_modified_byToUser: InternalEmailTemplate[];
    InsurancePolicy_InsurancePolicy_created_byToUser: InsurancePolicy[];
    InsurancePolicy_InsurancePolicy_modified_byToUser: InsurancePolicy[];
    InsurancePolicyCountry_InsurancePolicyCountry_created_byToUser: InsurancePolicyCountry[];
    InsurancePolicyCountry_InsurancePolicyCountry_modified_byToUser: InsurancePolicyCountry[];
    NamedPolicy_NamedPolicy_created_byToUser: NamedPolicy[];
    NamedPolicy_NamedPolicy_modified_byToUser: NamedPolicy[];
    CustomerTopUp_CustomerTopUp_created_byToUser: CustomerTopUp[];
    CustomerTopUp_CustomerTopUp_modified_byToUser: CustomerTopUp[];
    Invoice_Invoice_created_byToUser: Invoice[];
    Invoice_Invoice_modified_byToUser: Invoice[];
    InvoicePayment_InvoicePayment_created_byToUser: InvoicePayment[];
    InvoicePayment_InvoicePayment_modified_byToUser: InvoicePayment[];
    Log: Log[];
    Notification_Notification_created_byToUser: Notification[];
    Notification_Notification_modified_byToUser: Notification[];
    Notification_Notification_user_idToUser: Notification[];
    Payment_Payment_created_byToUser: Payment[];
    Payment_Payment_modified_byToUser: Payment[];
    Person_Person_created_byToUser: Person[];
    Person_Person_modified_byToUser: Person[];
    SMSVendor_SMSVendor_created_byToUser: SMSVendor[];
    SMSVendor_SMSVendor_modified_byToUser: SMSVendor[];
    SequenceContainer_SequenceContainer_created_byToUser: SequenceContainer[];
    SequenceContainer_SequenceContainer_modified_byToUser: SequenceContainer[];
    Session: Session[];
    Account_User_account_idToAccount: Account | null;
    UserImportMappings_created_by: UserImportMappings[];
    UserImportMappings_modified_by: UserImportMappings[];
    UserImportMappings_user_id: UserImportMappings[];
    User_User_created_byToUser: User | null;
    User_User_modified_byToUser: User | null;
    User_User_created_byToUser_User: User[];
    User_User_modified_byToUser_User: User[];
    BusinessUnit: BusinessUnit | null;
    BusinessUnit_BusinessUnit_created_byToUser: BusinessUnit[];
    BusinessUnit_BusinessUnit_modified_byToUser: BusinessUnit[];
    RolePermission_RolePermission_created_byToUser: RolePermission[];
    RolePermission_RolePermission_modified_byToUser: RolePermission[];
    UserPreferences: UserPreferences[];
    Report_Report_created_byToUser: Report[];
    Report_Report_modified_byToUser: Report[];
    ReportShare_ReportShare_shared_with_user_idToUser: ReportShare[];
    ReportShare_ReportShare_created_byToUser: ReportShare[];
    ReportExecution_ReportExecution_executed_byToUser: ReportExecution[];
    UserDefaultReport: UserDefaultReport[];
};

export type UserDefaultReport = {
    id: number;
    user_id: string;
    context: string;
    report_id: number;
    created_at: Date;
    modified_at: Date;
};

export type UserDefaultReportRelations = {
    User: User;
    Report: Report;
};

export type UserImportMappings = {
    id: string;
    user_id: string;
    mapping: JsonValue;
    name: string | null;
    is_default: boolean;
    created_at: Date;
    modified_at: Date;
    import_type: ImportType;
    created_by: string | null;
    modified_by: string | null;
};

export type UserImportMappingsRelations = {
    CreatedByUser: User | null;
    ModifiedByUser: User | null;
    User: User;
};

export type UserPreferences = {
    id: string;
    userId: string;
    preferenceKey: string;
    preferenceValue: JsonValue | null;
    created_at: Date;
    modified_at: Date;
};

export type UserPreferencesRelations = {
    User: User;
};

export type VerificationCode = {
    id: number;
    customer_uuid: string;
    code: string;
    expires_at: Date;
    created_at: Date;
};

export type VerificationToken = {
    id: string;
    identifier: string;
    token: string;
    expires: Date;
    created_at: Date;
    modified_at: Date;
};
