/**
 * Report metadata structure matching the metadata API
 * This file contains static metadata definitions for report tables and fields
 */

export interface TableMetadata {
    name: string;
    label: string;
    fields: FieldMetadata[];
    /** When true, table is hidden from the report builder table picker (e.g. relation/lookup tables). */
    hidden?: boolean;
}

export interface FieldMetadata {
    name: string;
    type: string;
    label: string;
    options?: string[];
    translationKey?: string; // Translation key (e.g., "customer_code", "details_customer")
    translationNamespace?: string; // Translation namespace (e.g., "customers", "disputes", "common")
    enumValueKeyPrefix?: string; // Prefix for enum value translation keys (e.g., "status", "dispute_status")
    // If not provided, uses field name. Used to construct keys like: values.{enumValueKeyPrefix}_{value}
}

export const REPORT_METADATA: { tables: TableMetadata[] } = {
    tables: [
        {
            name: "Customer",
            label: "Customers",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "customer_number",
                    type: "string",
                    label: "Customer Code",
                    translationKey: "customer_number",
                    translationNamespace: "customers",
                },
                {
                    name: "collection_status",
                    type: "enum",
                    label: "Status",
                    translationKey: "status",
                    translationNamespace: "common",
                    enumValueKeyPrefix: "status",
                    options: ["Active", "Inactive"],
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
                {
                    name: "type",
                    type: "enum",
                    label: "Type",
                    translationKey: "type",
                    translationNamespace: "customers",
                    enumValueKeyPrefix: "type",
                    options: ["Person", "Company"],
                },
                {
                    name: "category",
                    type: "enum",
                    label: "Category",
                    translationKey: "category",
                    translationNamespace: "customers",
                    enumValueKeyPrefix: "category",
                    options: [
                        "Automated",
                        "Promise_to_pay",
                        "Dispute",
                        "Agent",
                        "Legal",
                    ],
                },
                {
                    name: "total_due_amount",
                    type: "number",
                    label: "Total Due Amount",
                    translationKey: "total_due_amount",
                    translationNamespace: "customers",
                },
                {
                    name: "total_invoices_overdue",
                    type: "number",
                    label: "Total Overdue Amount",
                    translationKey: "total_invoices_overdue",
                    translationNamespace: "customers",
                },
                {
                    name: "number_of_overdue_invoices",
                    type: "number",
                    label: "Number of Overdue Invoices",
                    translationKey: "no_of_overdue_invoices",
                    translationNamespace: "customers",
                },
                {
                    name: "no_of_due_invoices",
                    type: "number",
                    label: "Number of Due Invoices",
                    translationKey: "no_of_due_invoices",
                    translationNamespace: "customers",
                },
                {
                    name: "phone",
                    type: "string",
                    label: "Phone",
                    translationKey: "phone",
                    translationNamespace: "customers",
                },
                {
                    name: "crn",
                    type: "string",
                    label: "CRN",
                    translationKey: "crn",
                    translationNamespace: "customers",
                },
                {
                    name: "email",
                    type: "string",
                    label: "Email",
                    translationKey: "email",
                    translationNamespace: "common",
                },
                {
                    name: "address_line1",
                    type: "string",
                    label: "Address Line 1",
                    translationKey: "address_1",
                    translationNamespace: "customers",
                },
                {
                    name: "address_line2",
                    type: "string",
                    label: "Address Line 2",
                    translationKey: "address_2",
                    translationNamespace: "customers",
                },
                {
                    name: "city",
                    type: "string",
                    label: "City",
                    translationKey: "city",
                    translationNamespace: "customers",
                },
                {
                    name: "postal_code",
                    type: "string",
                    label: "Postal Code",
                    translationKey: "postal_code",
                    translationNamespace: "customers",
                },
                {
                    name: "owner_id",
                    type: "user",
                    label: "Owner",
                    translationKey: "owner",
                    translationNamespace: "customers",
                },
                {
                    name: "name",
                    type: "string",
                    label: "Name",
                    translationKey: "name",
                    translationNamespace: "customers",
                },
                {
                    name: "parent_customer_name",
                    type: "string",
                    label: "Parent Customer",
                    translationKey: "parent_customer",
                    translationNamespace: "customers",
                },
                {
                    name: "Country.name",
                    type: "string",
                    label: "Country",
                    translationKey: "country",
                    translationNamespace: "common",
                },
                {
                    name: "State.name",
                    type: "string",
                    label: "State",
                    translationKey: "state",
                    translationNamespace: "customers",
                },
                {
                    name: "BusinessUnit.name",
                    type: "string",
                    label: "Business Unit",
                    translationKey: "business_unit",
                    translationNamespace: "customers",
                },
                {
                    name: "InsurancePolicy.policy_number",
                    type: "string",
                    label: "Insurance Policy",
                    translationKey: "insurance_policy",
                    translationNamespace: "customers",
                },
                {
                    name: "SequenceContainer.name",
                    type: "string",
                    label: "Automation Sequence",
                    translationKey: "sequence_container",
                    translationNamespace: "customers",
                },
                {
                    name: "customer_number_policy",
                    type: "string",
                    label: "Policy Customer Number",
                    translationKey: "customer_number_policy",
                    translationNamespace: "customers",
                },
                {
                    name: "approved_limit",
                    type: "number",
                    label: "Approved Limit",
                    translationKey: "approved_limit",
                    translationNamespace: "customers",
                },
                {
                    name: "approved_limit_expiration_date",
                    type: "date",
                    label: "Approved Limit Expiration Date",
                    translationKey: "approved_limit_expiration_date",
                    translationNamespace: "customers",
                },
                {
                    name: "limit_type",
                    type: "enum",
                    label: "Limit Type",
                    translationKey: "limit_type",
                    translationNamespace: "customers",
                    enumValueKeyPrefix: "limit_type",
                    options: ["DCL", "Named"],
                },
                {
                    name: "max_payment_term",
                    type: "number",
                    label: "Max Payment Term (Days)",
                    translationKey: "max_payment_term_days",
                    translationNamespace: "customers",
                },
                {
                    name: "max_allowed_mep",
                    type: "number",
                    label: "Max Allowed MEP (Days)",
                    translationKey: "max_allowed_mep_days",
                    translationNamespace: "customers",
                },
                {
                    name: "reporting_days",
                    type: "number",
                    label: "Reporting Days",
                    translationKey: "reporting_days",
                    translationNamespace: "customers",
                },
                {
                    name: "oldest_invoice_overdue_date",
                    type: "date",
                    label: "Oldest Overdue Invoice Date",
                    translationKey: "oldest_invoice_overdue_date",
                    translationNamespace: "customers",
                },
                {
                    name: "days_overdue",
                    type: "number",
                    label: "Days Overdue",
                    translationKey: "chart_details_days_overdue",
                    translationNamespace: "dashboard",
                },
                {
                    name: "overdue_block",
                    type: "boolean",
                    label: "Overdue Block",
                    translationKey: "overdue_block",
                    translationNamespace: "customers",
                },
                {
                    name: "policy_exclusion_reason",
                    type: "string",
                    label: "Policy Exclusion Reason",
                    translationKey: "policy_exclusion_reason",
                    translationNamespace: "customers",
                },
                {
                    name: "credit_score",
                    type: "number",
                    label: "Credit Score",
                    translationKey: "credit_score",
                    translationNamespace: "customers",
                },
                {
                    name: "credit_score_input_date",
                    type: "date",
                    label: "Credit Score Input Date",
                    translationKey: "credit_score_input_date",
                    translationNamespace: "customers",
                },
                {
                    name: "capacity_gap_amount",
                    type: "number",
                    label: "Capacity Gap",
                    translationKey: "capacity_gap_amount",
                    translationNamespace: "customers",
                },
                {
                    name: "zero_limit_date",
                    type: "date",
                    label: "Zero Limit Drop Date",
                    translationKey: "zero_limit_date",
                    translationNamespace: "customers",
                },
                {
                    name: "limit_expires_in_days",
                    type: "number",
                    label: "Limit Expires In (Days)",
                    translationKey: "limit_expires_in_days",
                    translationNamespace: "dashboard",
                },
                {
                    name: "top_up_total",
                    type: "number",
                    label: "Top-Up Cover",
                    translationKey: "top_up_cover_amount",
                    translationNamespace: "dashboard",
                },
                {
                    name: "effective_approved_limit",
                    type: "number",
                    label: "Effective Limit",
                    translationKey: "effective_limit",
                    translationNamespace: "dashboard",
                },
                {
                    name: "open_receivable_amount",
                    type: "number",
                    label: "Open AR",
                    translationKey: "open_ar",
                    translationNamespace: "dashboard",
                },
                {
                    name: "open_invoice_count",
                    type: "number",
                    label: "Open Invoices",
                    translationKey: "open_invoices",
                    translationNamespace: "dashboard",
                },
                {
                    name: "terms_breach_outstanding",
                    type: "number",
                    label: "Terms Breach Outstanding",
                    translationKey: "terms_breach_outstanding",
                    translationNamespace: "dashboard",
                },
                {
                    name: "policy_risk_allocated",
                    type: "number",
                    label: "Policy Risk (Allocated)",
                    translationKey: "policy_risk_allocated",
                    translationNamespace: "dashboard",
                },
                {
                    name: "limit_warning_summary",
                    type: "string",
                    label: "Warning Reason",
                    translationKey: "warning_reason",
                    translationNamespace: "dashboard",
                },
                {
                    name: "top_up_type",
                    type: "string",
                    label: "Top-Up Type",
                    translationKey: "top_up_type",
                    translationNamespace: "dashboard",
                },
                {
                    name: "top_up_value",
                    type: "number",
                    label: "Top-Up Value",
                    translationKey: "top_up_value",
                    translationNamespace: "dashboard",
                },
                {
                    name: "top_up_resolved_amount",
                    type: "number",
                    label: "Resolved Amount",
                    translationKey: "top_up_resolved_amount",
                    translationNamespace: "dashboard",
                },
                {
                    name: "top_up_end_date",
                    type: "date",
                    label: "End Date",
                    translationKey: "end_date",
                    translationNamespace: "customers",
                },
                {
                    name: "top_up_days_left",
                    type: "number",
                    label: "Expires In (Days)",
                    translationKey: "limit_expires_in_days",
                    translationNamespace: "dashboard",
                },
                {
                    name: "policy_daily_cost_change",
                    type: "number",
                    label: "Policy Daily Cost Change",
                    translationKey: "policy_daily_cost_change",
                    translationNamespace: "customers",
                },
                {
                    name: "policy_cost_currency",
                    type: "string",
                    label: "Policy Cost Currency",
                    translationKey: "policy_cost_currency",
                    translationNamespace: "customers",
                },
                {
                    name: "top_up_daily_cost_change",
                    type: "number",
                    label: "Top-Up Daily Cost Change",
                    translationKey: "top_up_daily_cost_change",
                    translationNamespace: "customers",
                },
                {
                    name: "top_up_cost_currency",
                    type: "string",
                    label: "Top-Up Cost Currency",
                    translationKey: "top_up_cost_currency",
                    translationNamespace: "customers",
                },
                {
                    name: "total_daily_cost_change",
                    type: "number",
                    label: "Total Daily Cost Change",
                    translationKey: "total_daily_cost_change",
                    translationNamespace: "customers",
                },
                {
                    name: "cost_calculation_method",
                    type: "enum",
                    label: "Cost Calculation Method",
                    translationKey: "cost_calculation_method",
                    translationNamespace: "customers",
                    enumValueKeyPrefix: "cost_calculation_method",
                    options: ["ActualSales", "Limit"],
                },
                {
                    name: "cost_percent",
                    type: "number",
                    label: "Insurance Premium Rate (%)",
                    translationKey: "cost_percent",
                    translationNamespace: "customers",
                },
                {
                    name: "registration_fee_percent",
                    type: "number",
                    label: "Registration Fee (%)",
                    translationKey: "registration_fee_percent",
                    translationNamespace: "customers",
                },
                {
                    name: "policy_cost_snapshot_date",
                    type: "date",
                    label: "Policy Cost Snapshot Date",
                    translationKey: "policy_cost_snapshot_date",
                    translationNamespace: "customers",
                },
            ],
        },
        {
            name: "Invoice",
            label: "Invoices",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "invoice_number",
                    type: "string",
                    label: "Invoice Number",
                    translationKey: "invoice_number",
                    translationNamespace: "invoices",
                },
                {
                    name: "amount",
                    type: "number",
                    label: "Amount",
                    translationKey: "amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "due_date",
                    type: "date",
                    label: "Due Date",
                    translationKey: "due_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "days_overdue",
                    type: "number",
                    label: "Days Overdue",
                    translationKey: "chart_details_days_overdue",
                    translationNamespace: "dashboard",
                },
                {
                    name: "days_until_due",
                    type: "number",
                    label: "Days Until Due",
                    translationKey: "chart_details_days_until_due",
                    translationNamespace: "dashboard",
                },
                {
                    name: "InsurancePolicy.policy_number",
                    type: "string",
                    label: "Insurance Policy",
                    translationKey: "insurance_policy",
                    translationNamespace: "customers",
                },
                {
                    name: "target_reporting_date",
                    type: "date",
                    label: "Target Reporting Date",
                    translationKey: "target_reporting_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "actual_reporting_date",
                    type: "date",
                    label: "Actual Reporting Date",
                    translationKey: "actual_reporting_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "target_mep_date",
                    type: "date",
                    label: "Target MEP Date",
                    translationKey: "target_mep_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "reported_status",
                    type: "enum",
                    label: "Reported Status",
                    translationKey: "reported_status",
                    translationNamespace: "invoices",
                    enumValueKeyPrefix: "reported_status",
                    options: ["Reported", "Acknowledge_Received"],
                },
                {
                    name: "reporting_comment",
                    type: "string",
                    label: "Reference / Comment",
                    translationKey: "reporting_comment",
                    translationNamespace: "invoices",
                },
                {
                    name: "reporting_captured_at",
                    type: "datetime",
                    label: "Reported At",
                    translationKey: "reported_at",
                    translationNamespace: "dashboard",
                },
                {
                    name: "days_left_for_reporting",
                    type: "number",
                    label: "Days Left for Reporting",
                    translationKey: "days_left_reporting",
                    translationNamespace: "dashboard",
                },
                {
                    name: "terms_breach_reason",
                    type: "string",
                    label: "Terms Breach Reason",
                    translationKey: "terms_breach_reason",
                    translationNamespace: "dashboard",
                },
                {
                    name: "reporting_breach",
                    type: "boolean",
                    label: "Reporting Breach",
                    translationKey: "reporting_breach",
                    translationNamespace: "invoices",
                },
                {
                    name: "ctv_payment_term",
                    type: "boolean",
                    label: "Created Terms Violation (Payment Term)",
                    translationKey: "ctv_payment_term",
                    translationNamespace: "invoices",
                },
                {
                    name: "ctv_customer_overdue_mep",
                    type: "boolean",
                    label: "Created Terms Violation (Customer Overdue MEP)",
                    translationKey: "ctv_customer_overdue_mep",
                    translationNamespace: "invoices",
                },
                {
                    name: "ctv_customer_excluded_from_policy",
                    type: "boolean",
                    label: "Created Terms Violation (Excluded From Policy)",
                    translationKey: "ctv_customer_excluded_from_policy",
                    translationNamespace: "invoices",
                },
                {
                    name: "ctv_outdated_dcl",
                    type: "boolean",
                    label: "Created Terms Violation (Outdated DCL)",
                    translationKey: "ctv_outdated_dcl",
                    translationNamespace: "invoices",
                },
                {
                    name: "ctv_invoice_after_policy_end",
                    type: "boolean",
                    label: "Created Terms Violation (After Policy End)",
                    translationKey: "ctv_invoice_after_policy_end",
                    translationNamespace: "invoices",
                },
                {
                    name: "oldest_overdue_invoice_date",
                    type: "date",
                    label: "Oldest Overdue Invoice Date",
                    translationKey: "oldest_overdue_invoice_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "in_capacity_gap",
                    type: "boolean",
                    label: "In Capacity Gap",
                    translationKey: "in_capacity_gap",
                    translationNamespace: "invoices",
                },
                {
                    name: "capacity_gap_amount",
                    type: "number",
                    label: "Capacity Gap (Account Currency)",
                    translationKey: "capacity_gap_amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "capacity_gap_amount_limit",
                    type: "number",
                    label: "Capacity Gap (Policy Currency)",
                    translationKey: "capacity_gap_amount_limit",
                    translationNamespace: "invoices",
                },
                {
                    name: "capacity_gap_amount_date",
                    type: "date",
                    label: "Capacity Gap Rate Date",
                    translationKey: "capacity_gap_amount_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "status",
                    type: "enum",
                    label: "Status",
                    translationKey: "status",
                    translationNamespace: "common",
                    enumValueKeyPrefix: "invoice_status",
                    options: [
                        "Draft",
                        "Open",
                        "Due",
                        "Partially_Paid",
                        "Paid",
                        "Overdue",
                        "Void",
                        "Under_Dispute",
                        "Sent",
                        "Viewed",
                        "Cancelled",
                    ],
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
                {
                    name: "outstanding_debt",
                    type: "number",
                    label: "Outstanding Debt",
                    translationKey: "outstanding_debt",
                    translationNamespace: "invoices",
                },
                {
                    name: "total_paid",
                    type: "number",
                    label: "Total Paid",
                    translationKey: "total_paid",
                    translationNamespace: "invoices",
                },
                {
                    name: "invoice_date",
                    type: "date",
                    label: "Invoice Date",
                    translationKey: "invoice_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "last_payment_date",
                    type: "date",
                    label: "Last Payment Date",
                    translationKey: "last_payment_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_currency",
                    type: "string",
                    label: "Customer Currency",
                    translationKey: "customer_currency",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_amount",
                    type: "number",
                    label: "Customer Amount",
                    translationKey: "customer_amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_net_amount",
                    type: "number",
                    label: "Net Amount",
                    translationKey: "net_amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_total_paid",
                    type: "number",
                    label: "Customer Total Paid",
                    translationKey: "customer_total_paid",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_outstanding_debt",
                    type: "number",
                    label: "Customer Outstanding Debt",
                    translationKey: "customer_outstanding_debt",
                    translationNamespace: "invoices",
                },
            ],
        },
        {
            name: "Payment",
            label: "Payments",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "amount",
                    type: "number",
                    label: "Amount",
                    translationKey: "amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "payment_date",
                    type: "date",
                    label: "Payment Date",
                    translationKey: "payment_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "payment_method",
                    type: "string",
                    label: "Payment Method",
                    translationKey: "payment_method",
                    translationNamespace: "invoices",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
                {
                    name: "reference",
                    type: "string",
                    label: "Reference",
                    translationKey: "reference",
                    translationNamespace: "invoices",
                },
            ],
        },
        {
            name: "InvoicePayment",
            label: "Invoice Payments",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "amount",
                    type: "number",
                    label: "Amount",
                    translationKey: "amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_amount",
                    type: "number",
                    label: "Customer Amount",
                    translationKey: "customer_amount",
                    translationNamespace: "invoices",
                },
                {
                    name: "payment_date",
                    type: "date",
                    label: "Payment Date",
                    translationKey: "payment_date",
                    translationNamespace: "invoices",
                },
                {
                    name: "payment_method",
                    type: "string",
                    label: "Payment Method",
                    translationKey: "payment_method",
                    translationNamespace: "invoices",
                },
                {
                    name: "reference",
                    type: "string",
                    label: "Reference",
                    translationKey: "reference",
                    translationNamespace: "invoices",
                },
                {
                    name: "invoice_number",
                    type: "string",
                    label: "Invoice Number",
                    translationKey: "invoice_number",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_currency",
                    type: "string",
                    label: "Customer Currency",
                    translationKey: "customer_currency",
                    translationNamespace: "invoices",
                },
                {
                    name: "invoice_id",
                    type: "number",
                    label: "Invoice ID",
                    translationKey: "invoice_id",
                    translationNamespace: "invoices",
                },
                {
                    name: "customer_id",
                    type: "number",
                    label: "Customer ID",
                    translationKey: "customer_id",
                    translationNamespace: "customers",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
            ],
        },
        {
            name: "Contact",
            label: "Contacts",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "first_name",
                    type: "string",
                    label: "First Name",
                    translationKey: "first_name",
                    translationNamespace: "contacts",
                },
                {
                    name: "last_name",
                    type: "string",
                    label: "Last Name",
                    translationKey: "last_name",
                    translationNamespace: "contacts",
                },
                {
                    name: "email",
                    type: "string",
                    label: "Email",
                    translationKey: "email",
                    translationNamespace: "common",
                },
                {
                    name: "phone",
                    type: "string",
                    label: "Phone",
                    translationKey: "phone",
                    translationNamespace: "customers",
                },
                {
                    name: "mobile",
                    type: "string",
                    label: "Mobile",
                    translationKey: "mobile",
                    translationNamespace: "contacts",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
                {
                    name: "role",
                    type: "string",
                    label: "Role",
                    translationKey: "role",
                    translationNamespace: "contacts",
                },
                {
                    name: "status",
                    type: "enum",
                    label: "Status",
                    translationKey: "status",
                    translationNamespace: "common",
                    enumValueKeyPrefix: "status",
                    options: ["Active", "Inactive"],
                },
                {
                    name: "receives_standard_reminder",
                    type: "boolean",
                    label: "Standard Reminders",
                    translationKey: "standard_reminders",
                    translationNamespace: "contacts",
                },
                {
                    name: "receives_escalated_reminder",
                    type: "boolean",
                    label: "Escalated Reminders",
                    translationKey: "escalated_reminders",
                    translationNamespace: "contacts",
                },
                {
                    name: "full_name",
                    type: "string",
                    label: "Full Name",
                    translationKey: "full_name",
                    translationNamespace: "contacts",
                },
            ],
        },
        {
            name: "Activity",
            label: "Activities",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "type",
                    type: "enum",
                    label: "Type",
                    translationKey: "type",
                    translationNamespace: "activities",
                    enumValueKeyPrefix: "type",
                    // Full Prisma activity_type enum (needed for operational drills / builder)
                    options: [
                        "SMS",
                        "Email",
                        "Call",
                        "WhatsApp",
                        "Internal",
                        "Resolved",
                        "Dispute",
                        "Promise_to_pay",
                        "Agent",
                    ],
                },
                {
                    name: "status",
                    type: "enum",
                    label: "Status",
                    translationKey: "status",
                    translationNamespace: "common",
                    enumValueKeyPrefix: "status",
                    // Use Prisma enum values for activity_status to ensure filters work correctly
                    // Display labels are provided via translations (e.g., activities.values.status_scheduled)
                    options: [
                        "SCHEDULED",
                        "SENT",
                        "DELIVERED",
                        "FAILED",
                        "CANCELLED",
                        "PAUSED",
                        "BOUNCED",
                        "DISPUTE",
                        "COMPLETED",
                    ],
                },
                {
                    name: "system_generated",
                    type: "boolean",
                    label: "System Generated",
                    translationKey: "system_generated",
                    translationNamespace: "activities",
                },
                {
                    name: "created_by",
                    type: "user",
                    label: "Created By",
                    translationKey: "created_by",
                    translationNamespace: "common",
                },
                {
                    name: "call_outcome",
                    type: "enum",
                    label: "Call Outcome",
                    translationKey: "call_outcome",
                    translationNamespace: "activities",
                    enumValueKeyPrefix: "outcomes",
                    options: [
                        "no_answer",
                        "bad_number",
                        "schedule_follow_up",
                        "promise_to_pay",
                        "make_payment",
                        "open_dispute",
                        "add_new_contact",
                        "general",
                        "move_to_legal",
                        "generic_comment",
                    ],
                },
                {
                    name: "call_time",
                    type: "datetime",
                    label: "Call Time",
                    // Prefer dedicated key once added to activities i18n; label used as fallback.
                    translationKey: "call_time",
                    translationNamespace: "activities",
                },
                {
                    name: "call_direction",
                    type: "enum",
                    label: "Call Direction",
                    translationKey: "call_direction",
                    translationNamespace: "activities",
                    enumValueKeyPrefix: "call_direction",
                    options: ["incoming", "outgoing"],
                },
                {
                    name: "schedule_time",
                    type: "datetime",
                    label: "Schedule Time",
                    translationKey: "schedule_time",
                    translationNamespace: "activities",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
                {
                    name: "title",
                    type: "string",
                    label: "Title",
                    translationKey: "title",
                    translationNamespace: "activities",
                },
                {
                    name: "content",
                    type: "string",
                    label: "Content",
                    translationKey: "content",
                    translationNamespace: "activities",
                },
                {
                    name: "actual_delivery_time",
                    type: "datetime",
                    label: "Actual Delivery Time",
                    translationKey: "actual_delivery_time",
                    translationNamespace: "activities",
                },
                {
                    name: "last_sent_time",
                    type: "datetime",
                    label: "Last Sent Time",
                    translationKey: "last_sent_time",
                    translationNamespace: "activities",
                },
            ],
        },
        {
            name: "Person",
            label: "Person",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "first_name",
                    type: "string",
                    label: "First Name",
                    translationKey: "first_name",
                    translationNamespace: "common",
                },
                {
                    name: "last_name",
                    type: "string",
                    label: "Last Name",
                    translationKey: "last_name",
                    translationNamespace: "common",
                },
                {
                    name: "full_name",
                    type: "string",
                    label: "Full Name",
                    translationKey: "full_name",
                    translationNamespace: "common",
                },
                {
                    name: "date_of_birth",
                    type: "date",
                    label: "Date of Birth",
                    translationKey: "date_of_birth",
                    translationNamespace: "common",
                },
                {
                    name: "identification_number",
                    type: "string",
                    label: "Identification Number",
                    translationKey: "identification_number",
                    translationNamespace: "common",
                },
                {
                    name: "mobile",
                    type: "string",
                    label: "Mobile",
                    translationKey: "mobile",
                    translationNamespace: "common",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
            ],
        },
        {
            name: "Company",
            label: "Company",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "name",
                    type: "string",
                    label: "Name",
                    translationKey: "name",
                    translationNamespace: "customers",
                },
                {
                    name: "company_number",
                    type: "string",
                    label: "Company Number",
                    translationKey: "company_number",
                    translationNamespace: "accounts",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
            ],
        },
        {
            name: "Dispute",
            label: "Disputes",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
                {
                    name: "closed_at",
                    type: "datetime",
                    label: "Closed At",
                    translationKey: "closed_at",
                    translationNamespace: "disputes",
                },
                {
                    name: "created_by",
                    type: "user",
                    label: "Created By",
                    translationKey: "created_by",
                    translationNamespace: "common",
                },
                {
                    name: "owner_id",
                    type: "user",
                    label: "Owner",
                    translationKey: "owner",
                    translationNamespace: "common",
                },
                {
                    name: "modified_by",
                    type: "user",
                    label: "Modified By",
                    translationKey: "modified_by",
                    translationNamespace: "common",
                },
                {
                    name: "dispute_number",
                    type: "number",
                    label: "Dispute Number",
                    translationKey: "details_dispute_number",
                    translationNamespace: "disputes",
                },
                {
                    name: "dispute_status",
                    type: "enum",
                    label: "Status",
                    translationKey: "details_dispute_status",
                    translationNamespace: "disputes",
                    enumValueKeyPrefix: "dispute_status",
                    options: [
                        "New",
                        "Under_Review",
                        "Awaiting_Update",
                        "Resolved",
                        "Cancelled",
                    ],
                },
                {
                    name: "dispute_resolution",
                    type: "enum",
                    label: "Resolution",
                    translationKey: "resolution_resolution",
                    translationNamespace: "disputes",
                    enumValueKeyPrefix: "status",
                    options: [
                        "Denied",
                        "Accepted_Settled_partly",
                        "Accepted_Settled_in_full",
                        "Accepted",
                        "Cancelled",
                        "Admin_Fixed_Balance_Unchanged",
                    ],
                },
                {
                    name: "dispute_reason",
                    type: "string",
                    label: "Dispute Reason",
                    translationKey: "details_dispute_reason",
                    translationNamespace: "disputes",
                },
                {
                    name: "assigned_to",
                    type: "user",
                    label: "Assigned To",
                    translationKey: "assignment_assigned_user",
                    translationNamespace: "disputes",
                },
                {
                    name: "amount_in_dispute",
                    type: "amount",
                    label: "Amount in Dispute",
                    translationKey: "details_amount_in_dispute",
                    translationNamespace: "disputes",
                },
                {
                    name: "days_past_due",
                    type: "number",
                    label: "Days Past Due",
                    translationKey: "details_days_past_due",
                    translationNamespace: "disputes",
                },
                {
                    name: "customer_comment",
                    type: "string",
                    label: "Customer Comment",
                    translationKey: "customer_comment",
                    translationNamespace: "disputes",
                },
                {
                    name: "resolution_comment",
                    type: "string",
                    label: "Resolution Comment",
                    translationKey: "resolution_resolution_comment",
                    translationNamespace: "disputes",
                },
                {
                    name: "contact_first_name",
                    type: "string",
                    label: "Contact First Name",
                    translationKey: "details_first_name",
                    translationNamespace: "disputes",
                },
                {
                    name: "contact_last_name",
                    type: "string",
                    label: "Contact Last Name",
                    translationKey: "details_last_name",
                    translationNamespace: "disputes",
                },
                {
                    name: "contact_email",
                    type: "string",
                    label: "Contact Email",
                    translationKey: "details_email",
                    translationNamespace: "disputes",
                },
                {
                    name: "contact_mobile",
                    type: "string",
                    label: "Contact Mobile",
                    translationKey: "details_mobile",
                    translationNamespace: "disputes",
                },
            ],
        },
        {
            name: "CustomerCollectionPeriod",
            label: "Collection Periods",
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "customer_id",
                    type: "number",
                    label: "Customer ID",
                    translationKey: "customer_id",
                    translationNamespace: "customers",
                },
                {
                    name: "period_start_date",
                    type: "date",
                    label: "Period Start Date",
                    translationKey: "period_start_date",
                    translationNamespace: "customers",
                },
                {
                    name: "period_end_date",
                    type: "date",
                    label: "Period End Date",
                    translationKey: "period_end_date",
                    translationNamespace: "customers",
                },
                {
                    name: "promise_to_pay_date",
                    type: "date",
                    label: "Promise to Pay Date",
                    translationKey: "promise_to_pay_date",
                    translationNamespace: "dashboard",
                },
                {
                    name: "promise_to_pay_amount",
                    type: "number",
                    label: "Promise to Pay Amount",
                    translationKey: "promise_to_pay_amount",
                    translationNamespace: "dashboard",
                },
                {
                    name: "currency",
                    type: "string",
                    label: "Currency",
                    translationKey: "currency",
                    translationNamespace: "common",
                },
                {
                    name: "current_category",
                    type: "enum",
                    label: "Current Category",
                    translationKey: "category",
                    translationNamespace: "customers",
                    enumValueKeyPrefix: "category",
                    options: [
                        "Automated",
                        "Promise_to_pay",
                        "Dispute",
                        "Agent",
                        "Legal",
                    ],
                },
                {
                    name: "total_outstanding_amount",
                    type: "number",
                    label: "Total Outstanding Amount",
                    translationKey: "total_outstanding_amount",
                    translationNamespace: "customers",
                },
                {
                    name: "promise_to_pay_count",
                    type: "number",
                    label: "Promise to Pay Count",
                    translationKey: "promise_to_pay_count",
                    translationNamespace: "dashboard",
                },
                {
                    name: "created_at",
                    type: "datetime",
                    label: "Created At",
                    translationKey: "created_at",
                    translationNamespace: "common",
                },
                {
                    name: "modified_at",
                    type: "datetime",
                    label: "Modified At",
                    translationKey: "modified_at",
                    translationNamespace: "common",
                },
            ],
        },
        {
            name: "AccountBankAccounts",
            label: "Bank Accounts",
            hidden: true,
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "bank_name",
                    type: "string",
                    label: "Bank Name",
                    translationKey: "bank_name",
                    translationNamespace: "bank_accounts",
                },
                {
                    name: "city",
                    type: "string",
                    label: "City",
                    translationKey: "city",
                    translationNamespace: "bank_accounts",
                },
                {
                    name: "account_number",
                    type: "string",
                    label: "Account Number",
                    translationKey: "account_number",
                    translationNamespace: "bank_accounts",
                },
                {
                    name: "beneficiary_name",
                    type: "string",
                    label: "Beneficiary Name",
                    translationKey: "beneficiary_name",
                    translationNamespace: "bank_accounts",
                },
            ],
        },
        {
            name: "Country",
            label: "Countries",
            hidden: true,
            fields: [
                {
                    name: "id",
                    type: "number",
                    label: "ID",
                    translationKey: "id",
                    translationNamespace: "common",
                },
                {
                    name: "name",
                    type: "string",
                    label: "Country",
                    translationKey: "country",
                    translationNamespace: "common",
                },
            ],
        },
    ],
};
